# Generated by Django 5.2.10 on 2026-01-30 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('country', models.CharField(choices=[('PL', 'Poland'), ('BY', 'Belarus'), ('UA', 'Ukraine'), ('OTHER', 'Other')], max_length=10)),
                ('city', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('business', 'Business'), ('construction', 'Construction'), ('agriculture', 'Agriculture'), ('service', 'Service'), ('tourism', 'Tourism')], max_length=30)),
                ('employment_type', models.CharField(choices=[('full', 'Full-time'), ('part', 'Part-time'), ('shift', 'Shift'), ('contract', 'Contract')], max_length=20)),
                ('salary', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=3000)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=100)),
                ('viber', models.CharField(blank=True, max_length=100)),
                ('telegram', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(choices=[('direct', 'Direct employer'), ('agency', 'Agency'), ('other', 'Other')], max_length=20)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
