# Generated by Django 5.2.10 on 2026-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_unlockrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="housing_type",
            field=models.CharField(choices=[("free", "Free"), ("paid", "Paid"), ("none", "None")], default="none", max_length=10),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="housing_cost",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
