# Generated by Django 5.2.10 on 2026-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_vacancy_housing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="creator_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="is_rejected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
    ]
