# Generated by Django 5.2.10 on 2026-02-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_vacancy_creator_token_rejection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='category',
            field=models.CharField(choices=[('construction', 'Construction'), ('agriculture', 'Agriculture'), ('warehouse', 'Warehouse'), ('logistics', 'Logistics'), ('manufacturing', 'Manufacturing'), ('hospitality', 'Hospitality'), ('cleaning', 'Cleaning'), ('retail', 'Retail'), ('transport', 'Transport'), ('healthcare', 'Healthcare'), ('it', 'IT'), ('service', 'Service'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='country',
            field=models.CharField(choices=[('PL', 'Poland'), ('DE', 'Germany'), ('FR', 'France'), ('ES', 'Spain'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('AT', 'Austria'), ('SE', 'Sweden'), ('FI', 'Finland'), ('DK', 'Denmark'), ('IE', 'Ireland'), ('PT', 'Portugal'), ('GR', 'Greece'), ('CZ', 'Czechia'), ('SK', 'Slovakia'), ('HU', 'Hungary'), ('RO', 'Romania'), ('BG', 'Bulgaria'), ('HR', 'Croatia'), ('SI', 'Slovenia'), ('LT', 'Lithuania'), ('LV', 'Latvia'), ('EE', 'Estonia'), ('LU', 'Luxembourg'), ('MT', 'Malta'), ('CY', 'Cyprus'), ('UK', 'United Kingdom'), ('CH', 'Switzerland'), ('US', 'USA'), ('CA', 'Canada'), ('UA', 'Ukraine'), ('BY', 'Belarus'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(choices=[('full', 'Full-time'), ('part', 'Part-time'), ('shift', 'Shift'), ('contract', 'Contract'), ('seasonal', 'Seasonal'), ('temporary', 'Temporary'), ('internship', 'Internship')], max_length=20),
        ),
    ]
