# Generated by Django 5.2.10 on 2026-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_vacancy_creator_token_rejection"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="experience_required",
            field=models.CharField(choices=[("with", "With experience"), ("without", "Without experience")], default="without", max_length=10),
        ),
    ]
