# Generated by Django 5.2.10 on 2026-02-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_vacancy_category_alter_vacancy_country_and_more'),
        ('jobs', '0006_vacancy_experience_required'),
    ]

    operations = [
    ]
