# Generated by Django 5.2.10 on 2026-02-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_phone_auth_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='pending_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='target_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('reset', 'Reset password'), ('link_email', 'Link email')], default='register', max_length=20),
        ),
    ]
