# Generated by Django 5.2.10 on 2026-02-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_vacancy_editing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary_currency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('PLN', 'PLN'), ('USD', 'USD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('GBP', 'GBP'), ('UAH', 'UAH'), ('BYN', 'BYN'), ('CZK', 'CZK'), ('HUF', 'HUF'), ('RON', 'RON'), ('BGN', 'BGN'), ('SEK', 'SEK'), ('DKK', 'DKK')], max_length=3),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_hours_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_tax_type',
            field=models.CharField(blank=True, choices=[('brutto', 'Brutto'), ('netto', 'Netto')], max_length=6),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
