# Generated by Django 5.2.10 on 2026-02-14 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_vacancy_salary_currency_vacancy_salary_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam/advertising'), ('fake', 'Fake'), ('abuse', 'Abuse'), ('wrong_info', 'Wrong information'), ('contacts', 'Invalid contacts'), ('not_actual', 'Not actual'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_complaints', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='jobs.vacancy')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='jobs_compla_status_abd568_idx'), models.Index(fields=['vacancy', 'status'], name='jobs_compla_vacancy_8b702c_idx'), models.Index(fields=['reason', 'created_at'], name='jobs_compla_reason_66bbd3_idx')],
            },
        ),
    ]
