# Generated by Django 5.2.10 on 2026-02-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_complaintactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='vacancy_revision_snapshot',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
