# Generated by Django 5.2.10 on 2026-02-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_complaint_vacancy_revision_snapshot_vacancy_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='last_moderator_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='moderation_baseline',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
