# Generated by Django 5.2.10 on 2026-02-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0016_vacancy_last_moderator_rejection_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="deleted_by_moderator_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="is_deleted_by_moderator",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="moderator_deleted_state",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
