# Generated by Django 5.2.10 on 2026-02-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0017_vacancy_moderator_soft_delete_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaintactionlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("delete_forever", "Delete vacancy forever"),
                    ("reject", "Reject vacancy"),
                    ("restore", "Restore vacancy"),
                ],
                max_length=20,
            ),
        ),
    ]
