# Generated by Django 5.2.10 on 2026-03-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_alter_vacancy_category_add_freelance'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='city_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='vacancyalertsubscription',
            name='city_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
