# Generated by Django 5.2.10 on 2026-03-20 19:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_vacancy_city_code_vacancyalertsubscription_city_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='last_owner_resume_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='owner_resume_count_day',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='owner_resume_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VacancyModerationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField()),
                ('trigger_type', models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('restore', 'Restore'), ('resume_expired', 'Resume expired'), ('moderator_resubmit', 'Moderator resubmit')], max_length=24)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('extra_context', models.JSONField(blank=True, default=dict)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_vacancy_moderation_attempts', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_vacancy_moderation_attempts', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_attempts', to='jobs.vacancy')),
            ],
            options={
                'ordering': ('-submitted_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('vacancy', 'attempt_no'), name='uniq_vacancy_moderation_attempt_no')],
            },
        ),
    ]
