# Generated by Django 5.2.10 on 2026-03-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_vacancy_last_owner_resume_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='driver_license_categories',
            field=models.CharField(blank=True, default='', max_length=48),
        ),
        migrations.AddField(
            model_name='vacancyalertsubscription',
            name='driver_license_categories',
            field=models.CharField(blank=True, default='', max_length=48),
        ),
    ]
