# Generated by Django 5.2.10 on 2026-03-31 18:03

from django.db import migrations, models


def seed_audience_countries_from_country(apps, schema_editor):
    Vacancy = apps.get_model('jobs', 'Vacancy')
    for vacancy in Vacancy.objects.all().only('id', 'country', 'audience_country_codes'):
        if vacancy.audience_country_codes:
            continue
        country = (vacancy.country or '').strip().upper()
        if not country:
            continue
        vacancy.audience_country_codes = f'|{country}|'
        vacancy.save(update_fields=['audience_country_codes'])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_vacancy_driver_license_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='audience_country_codes',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience_required',
            field=models.CharField(blank=True, choices=[('with', 'With experience'), ('without', 'Without experience')], default='', max_length=10),
        ),
        migrations.RunPython(
            seed_audience_countries_from_country,
            noop_reverse,
        ),
    ]
