# Generated by Django 5.2.10 on 2026-04-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_vacancy_audience_country_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyalertsubscription',
            name='audience_country_codes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
