# Generated by Django 5.2.10 on 2026-04-02 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _bootstrap_economy_objects(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL.split(".", 1)[0], settings.AUTH_USER_MODEL.split(".", 1)[1])
    Vacancy = apps.get_model("jobs", "Vacancy")
    EconomyConfig = apps.get_model("jobs", "EconomyConfig")
    UserWallet = apps.get_model("jobs", "UserWallet")
    UserMonetizationProfile = apps.get_model("jobs", "UserMonetizationProfile")

    EconomyConfig.objects.get_or_create(singleton_key=1)

    for user in User.objects.all().only("id"):
        UserWallet.objects.get_or_create(user_id=user.id)
        UserMonetizationProfile.objects.get_or_create(user_id=user.id)

    Vacancy.objects.filter(
        is_approved=True,
        approved_at__isnull=True,
    ).update(approved_at=models.F("published_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_vacancyalertsubscription_audience_country_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('vacancy_submit_price_credits', models.PositiveSmallIntegerField(default=3)),
                ('vacancy_edit_resubmit_price_credits', models.PositiveSmallIntegerField(default=2)),
                ('free_create_ad_submissions_limit', models.PositiveSmallIntegerField(default=3)),
                ('free_edit_ad_resubmissions_limit', models.PositiveSmallIntegerField(default=3)),
                ('employer_daily_free_submissions_limit', models.PositiveSmallIntegerField(default=3)),
                ('seeker_contact_discount_percent', models.PositiveSmallIntegerField(default=70)),
                ('contact_access_duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Economy config',
                'verbose_name_plural': 'Economy config',
            },
        ),
        migrations.AddField(
            model_name='unlockedcontact',
            name='charged_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unlockedcontact',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unlockedcontact',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='unlockedcontact',
            name='unlock_source',
            field=models.CharField(choices=[('paid', 'Paid credits'), ('ad', 'Rewarded ad'), ('subscription', 'Subscription'), ('admin', 'Admin')], default='paid', max_length=20),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('product_type', models.CharField(choices=[('credits', 'Credits pack'), ('employer_subscription', 'Employer subscription'), ('seeker_subscription', 'Seeker subscription')], max_length=32)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('shared', 'Shared')], default='shared', max_length=16)),
                ('store_product_id', models.CharField(blank=True, default='', max_length=160)),
                ('credit_amount', models.PositiveIntegerField(default=0)),
                ('duration_days', models.PositiveSmallIntegerField(default=0)),
                ('price_label', models.CharField(blank=True, default='', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['product_type', 'is_active'], name='jobs_storep_product_b8214e_idx'), models.Index(fields=['platform', 'is_active'], name='jobs_storep_platfor_0257ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserMonetizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_subscription_until', models.DateTimeField(blank=True, null=True)),
                ('seeker_subscription_until', models.DateTimeField(blank=True, null=True)),
                ('free_create_ad_submissions_used', models.PositiveSmallIntegerField(default=0)),
                ('free_edit_ad_resubmissions_used', models.PositiveSmallIntegerField(default=0)),
                ('employer_daily_submission_date', models.DateField(blank=True, null=True)),
                ('employer_daily_submissions_used', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monetization_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_credits', models.PositiveIntegerField(default=0)),
                ('bonus_credits', models.PositiveIntegerField(default=0)),
                ('lifetime_paid_credits', models.PositiveIntegerField(default=0)),
                ('lifetime_bonus_credits', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='VacancyContactAccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_unlock_mode', models.CharField(choices=[('paid_then_ad', 'Paid -> ad after timer'), ('paid_forever', 'Always paid'), ('ad_forever', 'Always ad')], default='ad_forever', max_length=20)),
                ('contact_unlock_timer_hours', models.PositiveSmallIntegerField(blank=True, choices=[(6, '6 hours'), (12, '12 hours'), (24, '24 hours'), (72, '72 hours')], null=True)),
                ('contact_unlock_price_credits', models.PositiveSmallIntegerField(default=3)),
                ('set_at', models.DateTimeField(auto_now=True)),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_vacancy_contact_policies', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_access_policy', to='jobs.vacancy')),
            ],
            options={
                'ordering': ['vacancy_id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('shared', 'Shared')], max_length=16)),
                ('product_type', models.CharField(choices=[('credits', 'Credits pack'), ('employer_subscription', 'Employer subscription'), ('seeker_subscription', 'Seeker subscription')], max_length=32)),
                ('store_product_id', models.CharField(blank=True, default='', max_length=160)),
                ('external_transaction_id', models.CharField(max_length=255, unique=True)),
                ('purchase_token', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('credits_granted', models.PositiveIntegerField(default=0)),
                ('entitlement_started_at', models.DateTimeField(blank=True, null=True)),
                ('entitlement_expires_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_records', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='jobs.storeproduct')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='jobs_purcha_user_id_3eb6d1_idx'), models.Index(fields=['status', 'created_at'], name='jobs_purcha_status_7f64c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('purchase_credit_pack', 'Purchase credit pack'), ('manual_grant', 'Manual grant'), ('manual_charge', 'Manual charge'), ('rewarded_ad', 'Rewarded ad'), ('vacancy_submit', 'Vacancy submit'), ('vacancy_edit_resubmit', 'Vacancy edit resubmit'), ('contact_unlock', 'Contact unlock'), ('subscription_activation', 'Subscription activation'), ('subscription_bonus', 'Subscription bonus'), ('refund', 'Refund'), ('system_adjustment', 'System adjustment')], max_length=40)),
                ('delta_paid_credits', models.IntegerField(default=0)),
                ('delta_bonus_credits', models.IntegerField(default=0)),
                ('balance_paid_after', models.PositiveIntegerField(default=0)),
                ('balance_bonus_after', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='jobs.vacancy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='jobs.userwallet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='jobs_wallet_user_id_a36500_idx'), models.Index(fields=['kind', 'created_at'], name='jobs_wallet_kind_2834db_idx')],
            },
        ),
        migrations.RunPython(_bootstrap_economy_objects, migrations.RunPython.noop),
    ]
