# Generated by Django 5.2.10 on 2026-04-04 14:50

from django.db import migrations, models


def backfill_paid_window_started_at(apps, schema_editor):
    VacancyContactAccessPolicy = apps.get_model("jobs", "VacancyContactAccessPolicy")
    for policy in VacancyContactAccessPolicy.objects.select_related("vacancy").all():
        if policy.contact_unlock_mode != "paid_then_ad" or policy.paid_window_started_at is not None:
            continue
        vacancy = getattr(policy, "vacancy", None)
        anchor = getattr(vacancy, "approved_at", None) or getattr(vacancy, "published_at", None)
        if anchor is None:
            continue
        policy.paid_window_started_at = anchor
        policy.save(update_fields=["paid_window_started_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_economyconfig_unlockedcontact_charged_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancycontactaccesspolicy',
            name='paid_window_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_paid_window_started_at, migrations.RunPython.noop),
    ]
