# Generated by Django 5.2.10 on 2026-04-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0035_vacancycontactaccesspolicy_paid_window_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancycontactaccesspolicy',
            name='contact_unlock_paid_click_limit',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(5, '5 paid opens'), (10, '10 paid opens'), (20, '20 paid opens'), (50, '50 paid opens'), (100, '100 paid opens')], null=True),
        ),
    ]
