# Generated by Django 5.2.10 on 2026-04-06 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_vacancycontactaccesspolicy_contact_unlock_paid_click_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('preset_codes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_vacancy_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_reviews', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='jobs.vacancy')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['employer', 'updated_at'], name='jobs_vacanc_employe_0f6ce0_idx'), models.Index(fields=['vacancy', 'updated_at'], name='jobs_vacanc_vacancy_d21fc1_idx'), models.Index(fields=['reviewer', 'updated_at'], name='jobs_vacanc_reviewe_f3322f_idx')],
                'constraints': [models.UniqueConstraint(fields=('reviewer', 'vacancy'), name='jobs_unique_reviewer_vacancy_review')],
            },
        ),
    ]
