# Generated by Django 5.2.10 on 2026-05-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0039_vacancy_additional_phone_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='apple_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
