# Generated by Django 5.2.10 on 2026-06-24 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0040_userprofile_apple_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorNotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('vacancy_pending', 'Vacancy pending moderation')], default='vacancy_pending', max_length=40)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped_no_device', 'Skipped (no device)'), ('skipped_not_configured', 'Skipped (provider not configured)')], max_length=40)),
                ('device_platform', models.CharField(blank=True, default='', max_length=20)),
                ('device_token_tail', models.CharField(blank=True, default='', max_length=12)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('error_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_notification_deliveries', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_notification_deliveries', to='jobs.vacancy')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'status', 'created_at'], name='jobs_modera_kind_ef010b_idx'), models.Index(fields=['vacancy', 'kind', 'created_at'], name='jobs_modera_vacancy_674dd2_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'vacancy', 'kind'), name='jobs_unique_moderator_notification')],
            },
        ),
    ]
