# Generated by Django 5.2.10 on 2026-07-10 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0042_free_ad_forever_contact_policies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='country',
            field=models.CharField(choices=[('PL', 'Poland'), ('DE', 'Germany'), ('FR', 'France'), ('ES', 'Spain'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('AT', 'Austria'), ('SE', 'Sweden'), ('FI', 'Finland'), ('DK', 'Denmark'), ('IE', 'Ireland'), ('PT', 'Portugal'), ('GR', 'Greece'), ('CZ', 'Czechia'), ('SK', 'Slovakia'), ('HU', 'Hungary'), ('RO', 'Romania'), ('BG', 'Bulgaria'), ('HR', 'Croatia'), ('SI', 'Slovenia'), ('LT', 'Lithuania'), ('LV', 'Latvia'), ('EE', 'Estonia'), ('LU', 'Luxembourg'), ('MT', 'Malta'), ('CY', 'Cyprus'), ('UK', 'United Kingdom'), ('CH', 'Switzerland'), ('US', 'USA'), ('CA', 'Canada'), ('UA', 'Ukraine'), ('BY', 'Belarus'), ('AD', 'Andorra'), ('AE', 'United Arab Emirates'), ('AL', 'Albania'), ('AM', 'Armenia'), ('AU', 'Australia'), ('AZ', 'Azerbaijan'), ('BA', 'Bosnia and Herzegovina'), ('GE', 'Georgia'), ('IL', 'Israel'), ('IS', 'Iceland'), ('KG', 'Kyrgyzstan'), ('KR', 'South Korea'), ('KZ', 'Kazakhstan'), ('LI', 'Liechtenstein'), ('MC', 'Monaco'), ('MD', 'Moldova'), ('ME', 'Montenegro'), ('MK', 'North Macedonia'), ('NO', 'Norway'), ('NZ', 'New Zealand'), ('QA', 'Qatar'), ('RS', 'Serbia'), ('SA', 'Saudi Arabia'), ('SM', 'San Marino'), ('TJ', 'Tajikistan'), ('TR', 'Turkey'), ('UZ', 'Uzbekistan'), ('XK', 'Kosovo'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.CreateModel(
            name='PhoneVerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_e164', models.CharField(blank=True, db_index=True, max_length=20)),
                ('purpose', models.CharField(blank=True, db_index=True, max_length=20)),
                ('channel', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('approved', 'Approved'), ('invalid_phone', 'Invalid phone'), ('unsupported_country', 'Unsupported country'), ('too_many_requests', 'Too many requests'), ('delivery_failed', 'Delivery failed'), ('check_failed', 'Check failed'), ('phone_already_used', 'Phone already used'), ('auth_required', 'Auth required'), ('invalid_channel', 'Invalid channel'), ('invalid_purpose', 'Invalid purpose'), ('user_not_found', 'User not found')], db_index=True, max_length=32)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='jobs_phonev_user_id_5230f4_idx'), models.Index(fields=['phone_e164', '-created_at'], name='jobs_phonev_phone_e_bf3782_idx')],
            },
        ),
    ]
