# Generated by Django 5.2.10 on 2026-07-10 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0043_alter_vacancy_country_phoneverificationattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary_currency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('PLN', 'PLN'), ('USD', 'USD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('GBP', 'GBP'), ('UAH', 'UAH'), ('BYN', 'BYN'), ('CZK', 'CZK'), ('HUF', 'HUF'), ('RON', 'RON'), ('BGN', 'BGN'), ('SEK', 'SEK'), ('DKK', 'DKK'), ('NOK', 'NOK'), ('ISK', 'ISK'), ('RSD', 'RSD'), ('BAM', 'BAM'), ('MKD', 'MKD'), ('ALL', 'ALL'), ('MDL', 'MDL'), ('TRY', 'TRY'), ('GEL', 'GEL'), ('AMD', 'AMD'), ('AZN', 'AZN'), ('ILS', 'ILS'), ('AED', 'AED'), ('SAR', 'SAR'), ('QAR', 'QAR'), ('KZT', 'KZT'), ('KGS', 'KGS'), ('UZS', 'UZS'), ('KRW', 'KRW'), ('AUD', 'AUD'), ('NZD', 'NZD')], max_length=3),
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_vacancy_title', models.CharField(blank=True, default='', max_length=120)),
                ('candidate_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('employer_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_chat_conversations', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_chat_conversations', to=settings.AUTH_USER_MODEL)),
                ('initial_vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_chat_conversations', to='jobs.vacancy')),
            ],
            options={
                'ordering': ('-last_message_at', '-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1500)),
                ('has_external_links', models.BooleanField(default=False)),
                ('client_message_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='jobs.chatconversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChatReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or advertising'), ('scam', 'Scam or fraud'), ('abuse', 'Abuse or harassment'), ('inappropriate', 'Inappropriate content'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.chatconversation')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_chat_reports', to=settings.AUTH_USER_MODEL)),
                ('reported_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='jobs.chatmessage')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_chat_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_chat_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['candidate', 'last_message_at'], name='jobs_chatco_candida_0edd42_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['employer', 'last_message_at'], name='jobs_chatco_employe_566caa_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatconversation',
            constraint=models.UniqueConstraint(fields=('candidate', 'employer'), name='jobs_unique_candidate_employer_chat'),
        ),
        migrations.AddConstraint(
            model_name='chatconversation',
            constraint=models.CheckConstraint(condition=models.Q(('candidate', models.F('employer')), _negated=True), name='jobs_chat_candidate_and_employer_differ'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='jobs_chatme_convers_2a6dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'created_at'], name='jobs_chatme_sender__c361ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'client_message_id'), name='jobs_unique_chat_client_message'),
        ),
        migrations.AddIndex(
            model_name='chatreport',
            index=models.Index(fields=['status', 'created_at'], name='jobs_chatre_status_b0b86e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatreport',
            index=models.Index(fields=['reported_user', 'created_at'], name='jobs_chatre_reporte_f1a188_idx'),
        ),
        migrations.AddIndex(
            model_name='chatreport',
            index=models.Index(fields=['conversation', 'created_at'], name='jobs_chatre_convers_b1b11e_idx'),
        ),
    ]
