# Generated by Django 5.2.10 on 2026-07-11 08:44

import django.db.models.deletion
from django.db import migrations, models


def assign_public_nicknames(apps, schema_editor):
    UserProfile = apps.get_model("jobs", "UserProfile")
    for profile in UserProfile.objects.all().only("id", "user_id", "nickname").iterator():
        if not (profile.nickname or "").strip():
            profile.nickname = f"JobHub User {profile.user_id}"
            profile.save(update_fields=["nickname"])


def keep_current_nicknames(apps, schema_editor):
    # Generated nicknames are public profile data and must remain stable.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0044_add_internal_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='jobs.chatmessage'),
        ),
        migrations.RunPython(assign_public_nicknames, keep_current_nicknames),
    ]
