# Generated by Django 5.2.10 on 2026-07-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0047_vacancy_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='telegram_usernames',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
