# Generated by Django 5.2.10 on 2026-07-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0048_vacancy_telegram_usernames'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employer_verified',
            field=models.BooleanField(default=False),
        ),
    ]
