# Generated by Django 5.2.10 on 2026-07-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0049_userprofile_employer_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='pinned_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='pinned_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='promotion_kind',
            field=models.CharField(blank=True, choices=[('', 'Standard'), ('vip', 'VIP'), ('premium', 'Premium'), ('urgent', 'Urgent')], default='', max_length=10),
        ),
    ]
