# Generated by Django 5.2.10 on 2026-07-12 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0050_vacancy_pinned_from_vacancy_pinned_until_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerBoardPublishingAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_code', models.CharField(editable=False, max_length=16, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting employer confirmation'), ('active', 'Active'), ('revoked', 'Revoked by employer')], default='pending', max_length=12)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('accepted_user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('authorization_version', models.CharField(blank=True, default='', max_length=32)),
                ('authorization_text', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board_publishing_authorization', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_board_publishing_authorizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerBoardPublishingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('requested', 'Request created'), ('accepted', 'Employer accepted'), ('revoked', 'Employer revoked'), ('published', 'Vacancy published')], max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jobs.employerboardpublishingauthorization')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_publishing_events_performed', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_publishing_events', to='jobs.vacancy')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='employerboardpublishingauthorization',
            index=models.Index(fields=['status', 'updated_at'], name='jobs_employ_status_5cad3b_idx'),
        ),
        migrations.AddIndex(
            model_name='employerboardpublishingevent',
            index=models.Index(fields=['authorization', 'created_at'], name='jobs_employ_authori_5f3ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='employerboardpublishingevent',
            index=models.Index(fields=['vacancy', 'created_at'], name='jobs_employ_vacancy_ebc325_idx'),
        ),
    ]
