# Generated by Django 5.2.10 on 2026-09-08 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0051_employerboardpublishingauthorization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTranslationUsageMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-month',),
            },
        ),
        migrations.CreateModel(
            name='VacancyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('pl', 'Polish'), ('uk', 'Ukrainian')], max_length=2)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('detected_source_language', models.CharField(blank=True, default='', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=240)),
                ('city', models.CharField(blank=True, default='', max_length=160)),
                ('description', models.TextField(blank=True, default='', max_length=6000)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('provider_version', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('failed', 'Failed')], max_length=16)),
                ('error_code', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_cache', to='jobs.vacancy')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vacancy', 'target_language'), name='jobs_unique_vacancy_translation_language')],
            },
        ),
    ]
