# Generated by Django 5.2.10 on 2026-08-01 14:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display_role', models.CharField(blank=True, default='', max_length=80)),
                ('state', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('is_owner', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_memberships', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('organization_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SupportOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('legal_name', models.CharField(max_length=180)),
                ('display_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('verified_document_email', models.EmailField(blank=True, default='', max_length=254)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('display_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SupportAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('reason', models.CharField(choices=[('continue_connection', 'Continue connection'), ('transition_period', 'Transition period'), ('technical_help', 'Technical help')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=16)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_support_access_grants', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_support_access_grants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_access_grants', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_access_grants', to='support.supportorganization')),
            ],
            options={
                'ordering': ('-ends_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SupportAccessExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('duration_days', models.PositiveSmallIntegerField(choices=[(7, '7 days'), (14, '14 days'), (30, '30 days')])),
                ('reason', models.CharField(choices=[('continue_connection', 'Continue connection'), ('transition_period', 'Transition period'), ('technical_help', 'Technical help')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_support_extension_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_support_extensions', to='support.organizationmembership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_extension_requests', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_extension_requests', to='support.supportorganization')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='support.supportorganization'),
        ),
        migrations.CreateModel(
            name='MembershipInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invited_email', models.EmailField(db_index=True, max_length=254)),
                ('display_role', models.CharField(blank=True, default='', max_length=80)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_support_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_support_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_invitations', to='support.supportorganization')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(db_index=True, max_length=96)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_public_id', models.UUIDField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='support.supportorganization')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='InvitationPermissionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='support.membershipinvitation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('invitation', 'permission_code'), name='support_unique_invitation_permission')],
            },
        ),
        migrations.CreateModel(
            name='DelegablePermissionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('permission_code', models.CharField(max_length=64)),
                ('scope_kind', models.CharField(choices=[('organization', 'Organization')], default='organization', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_support_permissions', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegable_permission_grants', to='support.organizationmembership')),
            ],
            options={
                'indexes': [models.Index(fields=['membership', 'is_active'], name='support_del_members_aa4dfc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('membership', 'permission_code', 'scope_kind'), name='support_unique_active_delegable_permission')],
            },
        ),
        migrations.CreateModel(
            name='PermissionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('permission_code', models.CharField(max_length=64)),
                ('scope_kind', models.CharField(choices=[('organization', 'Organization')], default='organization', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_support_permissions', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='support.organizationmembership')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_support_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['membership', 'is_active'], name='support_per_members_6feca4_idx'), models.Index(fields=['permission_code', 'is_active'], name='support_per_permiss_d5d32a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('membership', 'permission_code', 'scope_kind'), name='support_unique_active_permission_grant')],
            },
        ),
        migrations.AddIndex(
            model_name='supportorganization',
            index=models.Index(fields=['status', 'updated_at'], name='support_sup_status_657c78_idx'),
        ),
        migrations.AddIndex(
            model_name='supportorganization',
            index=models.Index(fields=['legal_name'], name='support_sup_legal_n_56c097_idx'),
        ),
        migrations.AddIndex(
            model_name='supportaccessgrant',
            index=models.Index(fields=['user', 'status', 'ends_at'], name='support_sup_user_id_b3f392_idx'),
        ),
        migrations.AddIndex(
            model_name='supportaccessgrant',
            index=models.Index(fields=['organization', 'status', 'ends_at'], name='support_sup_organiz_3de046_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportaccessgrant',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('ends_at'))), name='support_access_grant_valid_period'),
        ),
        migrations.AddIndex(
            model_name='supportaccessextensionrequest',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='support_sup_organiz_5a7d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='supportaccessextensionrequest',
            index=models.Index(fields=['user', 'status', 'created_at'], name='support_sup_user_id_6406d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportaccessextensionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user',), name='support_unique_pending_extension_request_per_user'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['user', 'state'], name='support_org_user_id_a1b975_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'state'], name='support_org_organiz_e95d1b_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='support_unique_organization_member'),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_owner', True)), fields=('organization',), name='support_unique_organization_owner'),
        ),
        migrations.AddIndex(
            model_name='membershipinvitation',
            index=models.Index(fields=['invited_user', 'state'], name='support_mem_invited_84c27e_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipinvitation',
            index=models.Index(fields=['organization', 'state'], name='support_mem_organiz_19adb8_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipinvitation',
            index=models.Index(fields=['state', 'expires_at'], name='support_mem_state_82bd81_idx'),
        ),
        migrations.AddConstraint(
            model_name='membershipinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'pending')), fields=('organization', 'invited_email'), name='support_unique_pending_invitation_email'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organization', 'created_at'], name='support_aud_organiz_9c4037_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor', 'created_at'], name='support_aud_actor_i_da0cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['target_type', 'target_public_id'], name='support_aud_target__162854_idx'),
        ),
    ]
