# Generated by Django 5.2.10 on 2026-08-01 15:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0051_employerboardpublishingauthorization_and_more'),
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('revision', models.PositiveSmallIntegerField(default=1)),
                ('preferred_language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('pl', 'Polish'), ('uk', 'Ukrainian')], max_length=2)),
                ('citizenship_country_code', models.CharField(blank=True, default='', max_length=2)),
                ('current_country_code', models.CharField(blank=True, default='', max_length=2)),
                ('availability_note', models.CharField(blank=True, default='', max_length=500)),
                ('partner_reference_code', models.CharField(blank=True, default='', max_length=24)),
                ('consent_version', models.CharField(max_length=32)),
                ('consented_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='submitted', max_length=16)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SupportConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stage', models.CharField(choices=[('awaiting_support', 'Awaiting Support access'), ('manager_stage', 'Manager stage'), ('documents_stage', 'Documents stage'), ('coordinator_stage', 'Coordinator stage'), ('active_worker', 'Active worker'), ('limited_manager_access', 'Limited manager access'), ('closed', 'Closed')], default='awaiting_support', max_length=32)),
                ('visible_stage', models.CharField(blank=True, default='', max_length=80)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='support_connection', to='support.supportapplication')),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_connections', to='support.organizationmembership')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_connections', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_connections', to='support.supportorganization')),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SupportConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('manager', 'Manager'), ('coordinator', 'Coordinator'), ('driver', 'Driver'), ('group', 'Group'), ('jobhub', 'JobHub')], max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=160)),
                ('state', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='support.supportconnection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_conversations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_conversations', to='support.supportorganization')),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SupportConversationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('worker', 'Worker'), ('staff', 'Staff')], max_length=16)),
                ('can_send', models.BooleanField(default=True)),
                ('group_push_enabled', models.BooleanField(default=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='support.supportconversation')),
                ('organization_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_conversation_memberships', to='support.organizationmembership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_conversation_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('body', models.TextField(max_length=1500)),
                ('original_language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('pl', 'Polish'), ('uk', 'Ukrainian')], max_length=2)),
                ('client_message_id', models.UUIDField(default=uuid.uuid4)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportconversation')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SupportVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('internal_title', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('internal_position_limit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_vacancies', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_vacancies', to='support.supportorganization')),
                ('public_vacancy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_workflow', to='jobs.vacancy')),
            ],
            options={
                'ordering': ('organization_id', '-updated_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='supportconnection',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='support.supportvacancy'),
        ),
        migrations.AddField(
            model_name='supportapplication',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='support.supportvacancy'),
        ),
        migrations.CreateModel(
            name='BotContentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveSmallIntegerField()),
                ('source_language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('pl', 'Polish'), ('uk', 'Ukrainian')], max_length=2)),
                ('content', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_bot_revisions', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_support_bot_revisions', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_revisions', to='support.supportvacancy')),
            ],
            options={
                'ordering': ('vacancy_id', '-version'),
            },
        ),
        migrations.CreateModel(
            name='SupportApplicantReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference_code', models.CharField(max_length=24, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_applicant_reference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['reference_code'], name='support_sup_referen_eb2939_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartnerPairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('closed', 'Closed')], default='pending', max_length=16)),
                ('first_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('second_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_partner_pair_requests', to=settings.AUTH_USER_MODEL)),
                ('first_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_partner_pair_requests', to='support.supportapplication')),
                ('second_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_partner_pair_requests', to='support.supportapplication')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'updated_at'], name='support_par_state_99810e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('first_application', models.F('second_application')), _negated=True), name='support_partner_pair_requires_two_applications')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDecisionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('clarification_requested', 'Clarification requested'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], max_length=32)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_application_decision_events', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_events', to='support.supportapplication')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['application', 'created_at'], name='support_app_applica_8637ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmploymentExclusivityLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('released', 'Released')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_employment_locks', to=settings.AUTH_USER_MODEL)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_exclusivity_lock', to='support.supportconnection')),
            ],
            options={
                'indexes': [models.Index(fields=['candidate', 'state'], name='support_emp_candida_b40b78_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('candidate',), name='support_one_active_employment_lock_per_candidate')],
            },
        ),
        migrations.CreateModel(
            name='ConnectionStageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('previous_stage', models.CharField(choices=[('awaiting_support', 'Awaiting Support access'), ('manager_stage', 'Manager stage'), ('documents_stage', 'Documents stage'), ('coordinator_stage', 'Coordinator stage'), ('active_worker', 'Active worker'), ('limited_manager_access', 'Limited manager access'), ('closed', 'Closed')], max_length=32)),
                ('next_stage', models.CharField(choices=[('awaiting_support', 'Awaiting Support access'), ('manager_stage', 'Manager stage'), ('documents_stage', 'Documents stage'), ('coordinator_stage', 'Coordinator stage'), ('active_worker', 'Active worker'), ('limited_manager_access', 'Limited manager access'), ('closed', 'Closed')], max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_connection_stage_events', to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='support.supportconnection')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['connection', 'created_at'], name='support_con_connect_c59def_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='supportconversation',
            index=models.Index(fields=['organization', 'state', 'updated_at'], name='support_sup_organiz_6834a8_idx'),
        ),
        migrations.AddIndex(
            model_name='supportconversation',
            index=models.Index(fields=['connection', 'kind', 'state'], name='support_sup_connect_313813_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportconversation',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'manager')), fields=('connection', 'kind'), name='support_one_manager_conversation_per_connection'),
        ),
        migrations.AddIndex(
            model_name='supportconversationmember',
            index=models.Index(fields=['user', 'left_at'], name='support_sup_user_id_c72729_idx'),
        ),
        migrations.AddIndex(
            model_name='supportconversationmember',
            index=models.Index(fields=['conversation', 'left_at'], name='support_sup_convers_17faa9_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportconversationmember',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='support_unique_conversation_member'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='support_sup_convers_23198a_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'client_message_id'), name='support_unique_conversation_client_message'),
        ),
        migrations.AddIndex(
            model_name='supportvacancy',
            index=models.Index(fields=['organization', 'status', 'updated_at'], name='support_sup_organiz_38b22c_idx'),
        ),
        migrations.AddIndex(
            model_name='supportvacancy',
            index=models.Index(fields=['status', 'updated_at'], name='support_sup_status_c42cac_idx'),
        ),
        migrations.AddIndex(
            model_name='supportconnection',
            index=models.Index(fields=['candidate', 'stage', 'is_archived'], name='support_sup_candida_771e01_idx'),
        ),
        migrations.AddIndex(
            model_name='supportconnection',
            index=models.Index(fields=['organization', 'stage', 'is_archived'], name='support_sup_organiz_e3c99d_idx'),
        ),
        migrations.AddIndex(
            model_name='supportconnection',
            index=models.Index(fields=['vacancy', 'stage', 'is_archived'], name='support_sup_vacancy_0f5555_idx'),
        ),
        migrations.AddIndex(
            model_name='supportapplication',
            index=models.Index(fields=['vacancy', 'status', 'submitted_at'], name='support_sup_vacancy_151ee9_idx'),
        ),
        migrations.AddIndex(
            model_name='supportapplication',
            index=models.Index(fields=['candidate', 'status', 'submitted_at'], name='support_sup_candida_ad9f75_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportapplication',
            constraint=models.UniqueConstraint(fields=('vacancy', 'candidate', 'revision'), name='support_unique_application_revision'),
        ),
        migrations.AddConstraint(
            model_name='supportapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['submitted', 'under_review', 'approved'])), fields=('vacancy', 'candidate'), name='support_one_open_application_per_vacancy_candidate'),
        ),
        migrations.AddIndex(
            model_name='botcontentrevision',
            index=models.Index(fields=['vacancy', 'status', 'version'], name='support_bot_vacancy_1b8c28_idx'),
        ),
        migrations.AddConstraint(
            model_name='botcontentrevision',
            constraint=models.UniqueConstraint(fields=('vacancy', 'version'), name='support_unique_bot_revision_version'),
        ),
        migrations.AddConstraint(
            model_name='botcontentrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('vacancy',), name='support_one_published_bot_revision_per_vacancy'),
        ),
    ]
