# Generated by Django 5.2.10 on 2026-08-01 15:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0051_employerboardpublishingauthorization_and_more'),
        ('support', '0002_supportapplication_supportconnection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notification_code', models.CharField(max_length=64)),
                ('target_kind', models.CharField(choices=[('connection', 'Connection'), ('conversation', 'Conversation'), ('support_access', 'Support access')], max_length=32)),
                ('target_public_id', models.UUIDField()),
                ('target_key', models.CharField(max_length=160)),
                ('notification_namespace', models.CharField(default='support', max_length=40)),
                ('collapse_key', models.CharField(max_length=160)),
                ('dedupe_key', models.CharField(max_length=160, unique=True)),
                ('push_requested', models.BooleanField(default=True)),
                ('safe_context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_outbox_entries', to='support.supportorganization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_notification_outbox_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_in_app_notifications', to=settings.AUTH_USER_MODEL)),
                ('outbox', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notification', to='support.notificationoutbox')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PushDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('device_platform', models.CharField(blank=True, default='', max_length=20)),
                ('device_token_tail', models.CharField(blank=True, default='', max_length=12)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('native_notification_tag', models.CharField(blank=True, default='', max_length=180)),
                ('error_code', models.CharField(blank=True, default='', max_length=120)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_push_deliveries', to='jobs.pushdevice')),
                ('outbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_deliveries', to='support.notificationoutbox')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SupportMessageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('target_language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('pl', 'Polish'), ('uk', 'Ukrainian')], max_length=2)),
                ('translated_text', models.TextField(blank=True, default='', max_length=3000)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('provider_version', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('failed', 'Failed')], max_length=16)),
                ('error_code', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='support.supportmessage')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_support_message_translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='notificationoutbox',
            index=models.Index(fields=['status', 'created_at'], name='support_not_status_bc7b47_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationoutbox',
            index=models.Index(fields=['recipient', 'created_at'], name='support_not_recipie_8cee7c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationoutbox',
            index=models.Index(fields=['target_key', 'created_at'], name='support_not_target__96098c_idx'),
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['recipient', 'read_at', 'created_at'], name='support_ina_recipie_605a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='pushdelivery',
            index=models.Index(fields=['outbox', 'status'], name='support_pus_outbox__1dd45d_idx'),
        ),
        migrations.AddIndex(
            model_name='pushdelivery',
            index=models.Index(fields=['device', 'status'], name='support_pus_device__e15b04_idx'),
        ),
        migrations.AddConstraint(
            model_name='pushdelivery',
            constraint=models.UniqueConstraint(fields=('outbox', 'device'), name='support_unique_push_delivery_per_device'),
        ),
        migrations.AddIndex(
            model_name='supportmessagetranslation',
            index=models.Index(fields=['message', 'target_language', 'status'], name='support_sup_message_ac2bdf_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportmessagetranslation',
            constraint=models.UniqueConstraint(fields=('message', 'target_language'), name='support_unique_message_translation_language'),
        ),
    ]
