# Generated by Django 5.2.10 on 2026-08-01 16:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_notificationoutbox_inappnotification_pushdelivery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('site_id', 'label', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DriverVehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_driver_vehicle_assignments', to=settings.AUTH_USER_MODEL)),
                ('driver_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_vehicle_assignments', to='support.supportconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_vehicle_assignments', to='support.supportorganization')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_support_driver_vehicle_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-starts_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='HousingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='support.housingroom')),
            ],
            options={
                'ordering': ('room_id', 'label', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HousingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('internal_name', models.CharField(max_length=160)),
                ('country_code', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=120)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('street', models.CharField(max_length=160)),
                ('building', models.CharField(max_length=40)),
                ('rules_text', models.TextField(blank=True, default='', max_length=5000)),
                ('contact_name', models.CharField(blank=True, default='', max_length=160)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=48)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_housing_sites', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_sites', to='support.supportorganization')),
            ],
            options={
                'ordering': ('internal_name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='housingroom',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='support.housingsite'),
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff')], max_length=16)),
                ('label', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('housing_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='support.housingsite')),
            ],
            options={
                'ordering': ('route_id', 'sequence', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('internal_name', models.CharField(max_length=160)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('reservation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_transport_routes', to=settings.AUTH_USER_MODEL)),
                ('driver_vehicle_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='support.drivervehicleassignment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_routes', to='support.supportorganization')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_support_transport_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-starts_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TransportPassengerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('boarding_order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_passenger_assignments', to='support.supportconnection')),
                ('dropoff_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dropoff_passenger_assignments', to='support.routestop')),
                ('pickup_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_passenger_assignments', to='support.routestop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_assignments', to='support.transportroute')),
            ],
            options={
                'ordering': ('route_id', 'boarding_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='routestop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='support.transportroute'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('internal_name', models.CharField(max_length=120)),
                ('registration_identifier', models.CharField(max_length=64)),
                ('seat_capacity', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_vehicles', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='support.supportorganization')),
            ],
            options={
                'ordering': ('internal_name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='drivervehicleassignment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver_assignments', to='support.vehicle'),
        ),
        migrations.CreateModel(
            name='WorkProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('internal_name', models.CharField(max_length=160)),
                ('worker_visible_name', models.CharField(max_length=160)),
                ('instructions', models.TextField(blank=True, default='', max_length=5000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_work_projects', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_projects', to='support.supportorganization')),
            ],
            options={
                'ordering': ('internal_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WorkerProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('worker_role', models.CharField(blank=True, default='', max_length=160)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='support.supportconnection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_project_assignments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_project_assignments', to='support.supportorganization')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_support_project_assignments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_assignments', to='support.workproject')),
            ],
            options={
                'ordering': ('-starts_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Worksite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('internal_name', models.CharField(max_length=160)),
                ('country_code', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=120)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('street', models.CharField(max_length=160)),
                ('building', models.CharField(max_length=40)),
                ('instructions', models.TextField(blank=True, default='', max_length=5000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_worksites', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksites', to='support.supportorganization')),
            ],
            options={
                'ordering': ('internal_name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='workproject',
            name='worksite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='support.worksite'),
        ),
        migrations.AddField(
            model_name='transportroute',
            name='worksite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_routes', to='support.worksite'),
        ),
        migrations.CreateModel(
            name='HousingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('check_in_at', models.DateTimeField()),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_assignments', to='support.supportconnection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_housing_assignments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_assignments', to='support.supportorganization')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_support_housing_assignments', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='support.housingplace')),
            ],
            options={
                'ordering': ('-check_in_at', '-id'),
                'indexes': [models.Index(fields=['organization', 'state', 'check_in_at'], name='support_hou_organiz_6e4f91_idx'), models.Index(fields=['connection', 'state', 'check_in_at'], name='support_hou_connect_500d03_idx'), models.Index(fields=['place', 'state', 'check_in_at'], name='support_hou_place_i_dd5c6e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('check_out_at__isnull', True), ('check_in_at__lt', models.F('check_out_at')), _connector='OR'), name='support_housing_assignment_valid_period')],
            },
        ),
        migrations.AddIndex(
            model_name='housingplace',
            index=models.Index(fields=['room', 'is_active'], name='support_hou_room_id_7f205a_idx'),
        ),
        migrations.AddConstraint(
            model_name='housingplace',
            constraint=models.UniqueConstraint(fields=('room', 'label'), name='support_unique_housing_place_label_per_room'),
        ),
        migrations.AddIndex(
            model_name='housingsite',
            index=models.Index(fields=['organization', 'is_active', 'internal_name'], name='support_hou_organiz_6e96f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='housingsite',
            constraint=models.UniqueConstraint(fields=('organization', 'internal_name'), name='support_unique_housing_site_internal_name'),
        ),
        migrations.AddIndex(
            model_name='housingroom',
            index=models.Index(fields=['site', 'is_active'], name='support_hou_site_id_de2331_idx'),
        ),
        migrations.AddConstraint(
            model_name='housingroom',
            constraint=models.UniqueConstraint(fields=('site', 'label'), name='support_unique_housing_room_label_per_site'),
        ),
        migrations.AddConstraint(
            model_name='housingroom',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='support_housing_room_capacity_positive'),
        ),
        migrations.AddIndex(
            model_name='transportpassengerassignment',
            index=models.Index(fields=['connection', 'route'], name='support_tra_connect_ea7b94_idx'),
        ),
        migrations.AddIndex(
            model_name='transportpassengerassignment',
            index=models.Index(fields=['route', 'boarding_order'], name='support_tra_route_i_50959d_idx'),
        ),
        migrations.AddConstraint(
            model_name='transportpassengerassignment',
            constraint=models.UniqueConstraint(fields=('route', 'connection'), name='support_unique_transport_passenger_per_route'),
        ),
        migrations.AddConstraint(
            model_name='transportpassengerassignment',
            constraint=models.CheckConstraint(condition=models.Q(('boarding_order__gte', 1)), name='support_transport_passenger_boarding_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'sequence'), name='support_unique_transport_route_stop_sequence'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['organization', 'is_active', 'internal_name'], name='support_veh_organiz_3d10a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('organization', 'registration_identifier'), name='support_unique_vehicle_registration_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('seat_capacity__gte', 2)), name='support_vehicle_includes_driver_and_passenger'),
        ),
        migrations.AddIndex(
            model_name='drivervehicleassignment',
            index=models.Index(fields=['organization', 'state', 'starts_on'], name='support_dri_organiz_d8f94b_idx'),
        ),
        migrations.AddIndex(
            model_name='drivervehicleassignment',
            index=models.Index(fields=['driver_connection', 'state', 'starts_on'], name='support_dri_driver__274a79_idx'),
        ),
        migrations.AddIndex(
            model_name='drivervehicleassignment',
            index=models.Index(fields=['vehicle', 'state', 'starts_on'], name='support_dri_vehicle_8635d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='drivervehicleassignment',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('starts_on__lt', models.F('ends_on')), _connector='OR'), name='support_driver_vehicle_assignment_valid_period'),
        ),
        migrations.AddIndex(
            model_name='workerprojectassignment',
            index=models.Index(fields=['organization', 'state', 'starts_at'], name='support_wor_organiz_012a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprojectassignment',
            index=models.Index(fields=['connection', 'state', 'starts_at'], name='support_wor_connect_30e8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprojectassignment',
            index=models.Index(fields=['project', 'state', 'starts_at'], name='support_wor_project_a075ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='workerprojectassignment',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('starts_at__lt', models.F('ends_at')), _connector='OR'), name='support_project_assignment_valid_period'),
        ),
        migrations.AddIndex(
            model_name='worksite',
            index=models.Index(fields=['organization', 'is_active', 'internal_name'], name='support_wor_organiz_cc22e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='worksite',
            constraint=models.UniqueConstraint(fields=('organization', 'internal_name'), name='support_unique_worksite_internal_name'),
        ),
        migrations.AddIndex(
            model_name='workproject',
            index=models.Index(fields=['organization', 'is_active', 'internal_name'], name='support_wor_organiz_c22702_idx'),
        ),
        migrations.AddConstraint(
            model_name='workproject',
            constraint=models.UniqueConstraint(fields=('organization', 'internal_name'), name='support_unique_work_project_internal_name'),
        ),
        migrations.AddIndex(
            model_name='transportroute',
            index=models.Index(fields=['organization', 'state', 'starts_on'], name='support_tra_organiz_477ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='transportroute',
            index=models.Index(fields=['driver_vehicle_assignment', 'state', 'starts_on'], name='support_tra_driver__1fcf62_idx'),
        ),
        migrations.AddConstraint(
            model_name='transportroute',
            constraint=models.UniqueConstraint(fields=('organization', 'internal_name'), name='support_unique_transport_route_internal_name'),
        ),
        migrations.AddConstraint(
            model_name='transportroute',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('starts_on__lt', models.F('ends_on')), _connector='OR'), name='support_transport_route_valid_period'),
        ),
    ]
