# Generated by Django 5.2.10 on 2026-08-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_housingroom_drivervehicleassignment_housingplace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationoutbox',
            name='target_kind',
            field=models.CharField(choices=[('connection', 'Connection'), ('conversation', 'Conversation'), ('support_access', 'Support access'), ('housing_assignment', 'Housing assignment'), ('work_assignment', 'Work assignment'), ('transport_route', 'Transport route')], max_length=32),
        ),
    ]
