# Generated by Django 5.2.10 on 2026-08-05 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0014_supportconnection_has_driving_license'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='drivervehicleassignment',
            name='support_driver_vehicle_assignment_valid_period',
        ),
        migrations.RemoveConstraint(
            model_name='transportroute',
            name='support_transport_route_valid_period',
        ),
        migrations.AddConstraint(
            model_name='drivervehicleassignment',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('starts_on__lte', models.F('ends_on')), _connector='OR'), name='support_driver_vehicle_assignment_valid_period'),
        ),
        migrations.AddConstraint(
            model_name='transportroute',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('starts_on__lte', models.F('ends_on')), _connector='OR'), name='support_transport_route_valid_period'),
        ),
    ]
