# Generated by Django 5.2.10 on 2026-08-05 18:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0015_allow_single_day_transport_periods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('starts_at_time', models.TimeField()),
                ('ends_at_time', models.TimeField()),
                ('break_minutes', models.PositiveSmallIntegerField(default=0)),
                ('worker_label', models.CharField(blank=True, default='', max_length=160)),
                ('calendar_dates', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WorkerProjectScheduleTemplateSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='workproject',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='workproject',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='workproject',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=48),
        ),
        migrations.AddField(
            model_name='workproject',
            name='ends_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workproject',
            name='starts_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='workproject',
            name='worker_capacity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='workproject',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('starts_on__lte', models.F('ends_on')), _connector='OR'), name='support_work_project_valid_period'),
        ),
        migrations.AddField(
            model_name='projectscheduletemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_schedule_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectscheduletemplate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='support.workproject'),
        ),
        migrations.AddField(
            model_name='workerprojectscheduletemplateselection',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_template_selections', to='support.workerprojectassignment'),
        ),
        migrations.AddField(
            model_name='workerprojectscheduletemplateselection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_selections', to='support.projectscheduletemplate'),
        ),
        migrations.AddIndex(
            model_name='projectscheduletemplate',
            index=models.Index(fields=['project', 'is_active', 'name'], name='support_pro_project_7adc27_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectscheduletemplate',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='support_unique_project_schedule_template_name'),
        ),
        migrations.AddIndex(
            model_name='workerprojectscheduletemplateselection',
            index=models.Index(fields=['template', 'assignment'], name='support_wor_templat_8c083f_idx'),
        ),
        migrations.AddConstraint(
            model_name='workerprojectscheduletemplateselection',
            constraint=models.UniqueConstraint(fields=('assignment', 'template'), name='support_unique_worker_project_schedule_template'),
        ),
    ]
