# Generated by Django 5.2.10 on 2026-08-09 11:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_stable_transport_crews(apps, schema_editor):
    """Mirror every template-backed legacy route into the stable crew tables."""

    TransportCrew = apps.get_model("support", "TransportCrew")
    TransportCrewDriver = apps.get_model("support", "TransportCrewDriver")
    TransportCrewMember = apps.get_model("support", "TransportCrewMember")
    TransportCrewVehicle = apps.get_model("support", "TransportCrewVehicle")
    TransportRoute = apps.get_model("support", "TransportRoute")

    routes = TransportRoute.objects.filter(
        schedule_template__isnull=False,
        crew__isnull=True,
    ).select_related(
        "schedule_template",
        "driver_vehicle_assignment",
    )
    for route in routes.iterator():
        driver_assignment = route.driver_vehicle_assignment
        crew = TransportCrew.objects.create(
            organization_id=route.organization_id,
            project_id=route.schedule_template.project_id,
            schedule_template_id=route.schedule_template_id,
            internal_name=route.internal_name,
            starts_on=route.starts_on,
            ends_on=route.ends_on,
            state="archived" if route.state == "cancelled" else "active",
            created_by_id=route.created_by_id,
        )
        TransportCrewDriver.objects.create(
            crew_id=crew.id,
            driver_connection_id=driver_assignment.driver_connection_id,
            starts_on=route.starts_on,
            ends_on=route.ends_on,
            created_by_id=route.created_by_id,
        )
        TransportCrewVehicle.objects.create(
            crew_id=crew.id,
            vehicle_id=driver_assignment.vehicle_id,
            starts_on=route.starts_on,
            ends_on=route.ends_on,
            created_by_id=route.created_by_id,
        )
        members = []
        for passenger in route.passenger_assignments.all().iterator():
            members.append(
                TransportCrewMember(
                    crew_id=crew.id,
                    connection_id=passenger.connection_id,
                    starts_on=route.starts_on,
                    ends_on=route.ends_on,
                    boarding_order=passenger.boarding_order,
                    created_by_id=route.created_by_id,
                )
            )
        TransportCrewMember.objects.bulk_create(members)
        route.crew_id = crew.id
        route.save(update_fields=["crew"])


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0020_link_transport_crews_to_schedule_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('internal_name', models.CharField(blank=True, default='', max_length=160)),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_transport_crews', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_crews', to='support.supportorganization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_crews', to='support.workproject')),
                ('schedule_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_crews', to='support.projectscheduletemplate')),
            ],
            options={
                'ordering': ('project__internal_name', 'schedule_template__name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='scheduledworkshift',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_shifts', to='support.transportcrew'),
        ),
        migrations.AddField(
            model_name='transportroute',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_routes', to='support.transportcrew'),
        ),
        migrations.CreateModel(
            name='TransportCrewDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_transport_crew_drivers', to=settings.AUTH_USER_MODEL)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='support.transportcrew')),
                ('driver_connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_crew_driver_assignments', to='support.supportconnection')),
            ],
            options={
                'ordering': ('-starts_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TransportCrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('boarding_order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_crew_memberships', to='support.supportconnection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_transport_crew_members', to=settings.AUTH_USER_MODEL)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='support.transportcrew')),
            ],
            options={
                'ordering': ('crew_id', 'boarding_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TransportCrewScheduleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('work_date', models.DateField()),
                ('kind', models.CharField(choices=[('shift', 'Changed shift'), ('day_off', 'Day off'), ('cancelled', 'Cancelled shift')], max_length=16)),
                ('starts_at_time', models.TimeField(blank=True, null=True)),
                ('ends_at_time', models.TimeField(blank=True, null=True)),
                ('break_minutes', models.PositiveSmallIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_transport_crew_overrides', to=settings.AUTH_USER_MODEL)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_overrides', to='support.transportcrew')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_support_transport_crew_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('work_date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TransportCrewVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_transport_crew_vehicles', to=settings.AUTH_USER_MODEL)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to='support.transportcrew')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_crew_assignments', to='support.vehicle')),
            ],
            options={
                'ordering': ('-starts_on', '-id'),
            },
        ),
        migrations.RunPython(
            backfill_stable_transport_crews,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='transportcrew',
            index=models.Index(fields=['organization', 'state', 'starts_on'], name='support_tra_organiz_0a8fbb_idx'),
        ),
        migrations.AddIndex(
            model_name='transportcrew',
            index=models.Index(fields=['project', 'schedule_template', 'state'], name='support_tra_project_fd43de_idx'),
        ),
        migrations.AddConstraint(
            model_name='transportcrew',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('starts_on__lte', models.F('ends_on')), _connector='OR'), name='support_transport_crew_valid_period'),
        ),
        migrations.AddIndex(
            model_name='transportcrewdriver',
            index=models.Index(fields=['crew', 'starts_on'], name='support_tra_crew_id_a2615b_idx'),
        ),
        migrations.AddIndex(
            model_name='transportcrewdriver',
            index=models.Index(fields=['driver_connection', 'starts_on'], name='support_tra_driver__20867f_idx'),
        ),
        migrations.AddConstraint(
            model_name='transportcrewdriver',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('starts_on__lte', models.F('ends_on')), _connector='OR'), name='support_crew_driver_valid_period'),
        ),
        migrations.AddConstraint(
            model_name='transportcrewdriver',
            constraint=models.UniqueConstraint(condition=models.Q(('ends_on__isnull', True)), fields=('crew',), name='support_one_open_crew_driver'),
        ),
        migrations.AddIndex(
            model_name='transportcrewmember',
            index=models.Index(fields=['crew', 'starts_on', 'boarding_order'], name='support_tra_crew_id_6f963b_idx'),
        ),
        migrations.AddIndex(
            model_name='transportcrewmember',
            index=models.Index(fields=['connection', 'starts_on'], name='support_tra_connect_4f1e98_idx'),
        ),
        migrations.AddConstraint(
            model_name='transportcrewmember',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('starts_on__lte', models.F('ends_on')), _connector='OR'), name='support_crew_member_valid_period'),
        ),
        migrations.AddConstraint(
            model_name='transportcrewmember',
            constraint=models.CheckConstraint(condition=models.Q(('boarding_order__gte', 1)), name='support_crew_member_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='transportcrewmember',
            constraint=models.UniqueConstraint(condition=models.Q(('ends_on__isnull', True)), fields=('crew', 'connection'), name='support_one_open_crew_member'),
        ),
        migrations.AddIndex(
            model_name='transportcrewscheduleoverride',
            index=models.Index(fields=['crew', 'work_date', 'kind'], name='support_tra_crew_id_6d6cb3_idx'),
        ),
        migrations.AddConstraint(
            model_name='transportcrewscheduleoverride',
            constraint=models.UniqueConstraint(fields=('crew', 'work_date'), name='support_unique_crew_override_day'),
        ),
        migrations.AddConstraint(
            model_name='transportcrewscheduleoverride',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ends_at_time__isnull', False), ('kind', 'shift'), ('starts_at_time__isnull', False)), models.Q(('ends_at_time__isnull', True), ('kind__in', ('day_off', 'cancelled')), ('starts_at_time__isnull', True)), _connector='OR'), name='support_crew_override_payload_valid'),
        ),
        migrations.AddIndex(
            model_name='transportcrewvehicle',
            index=models.Index(fields=['crew', 'starts_on'], name='support_tra_crew_id_b040dc_idx'),
        ),
        migrations.AddIndex(
            model_name='transportcrewvehicle',
            index=models.Index(fields=['vehicle', 'starts_on'], name='support_tra_vehicle_c5d8d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='transportcrewvehicle',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('starts_on__lte', models.F('ends_on')), _connector='OR'), name='support_crew_vehicle_valid_period'),
        ),
        migrations.AddConstraint(
            model_name='transportcrewvehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('ends_on__isnull', True)), fields=('crew',), name='support_one_open_crew_vehicle'),
        ),
    ]
