# Generated by Django 5.2.10 on 2026-08-09 11:48

from django.conf import settings
from django.db import migrations, models


def link_existing_shifts_to_crews(apps, schema_editor):
    """Attach legacy template shifts to the crews created in migration 0021."""

    ScheduledWorkShift = apps.get_model("support", "ScheduledWorkShift")
    TransportRoute = apps.get_model("support", "TransportRoute")

    routes = TransportRoute.objects.filter(
        crew__isnull=False,
        schedule_template__isnull=False,
        state__in=("draft", "published"),
    ).select_related("driver_vehicle_assignment")
    for route in routes.iterator():
        participant_ids = [route.driver_vehicle_assignment.driver_connection_id]
        participant_ids.extend(
            route.passenger_assignments.values_list("connection_id", flat=True)
        )
        shifts = ScheduledWorkShift.objects.filter(
            organization_id=route.organization_id,
            connection_id__in=participant_ids,
            schedule_template_id=route.schedule_template_id,
            crew__isnull=True,
            work_date__gte=route.starts_on,
            state__in=("draft", "published"),
        )
        if route.ends_on is not None:
            shifts = shifts.filter(work_date__lte=route.ends_on)
        shifts.update(crew_id=route.crew_id)


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0021_add_stable_transport_crews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scheduledworkshift',
            name='support_one_current_scheduled_shift_per_day',
        ),
        migrations.AddConstraint(
            model_name='scheduledworkshift',
            constraint=models.UniqueConstraint(condition=models.Q(('crew__isnull', True), ('state__in', ('draft', 'published'))), fields=('connection', 'work_date'), name='support_one_legacy_shift_day'),
        ),
        migrations.AddConstraint(
            model_name='scheduledworkshift',
            constraint=models.UniqueConstraint(condition=models.Q(('crew__isnull', False), ('state__in', ('draft', 'published'))), fields=('connection', 'work_date', 'crew'), name='support_one_crew_shift_day'),
        ),
        migrations.RunPython(
            link_existing_shifts_to_crews,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
