# Generated by Django 5.2.10 on 2026-08-10 20:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0022_allow_multiple_crew_shifts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportCrewResourceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('work_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_transport_crew_resource_overrides', to=settings.AUTH_USER_MODEL)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_overrides', to='support.transportcrew')),
                ('driver_vehicle_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_crew_resource_overrides', to='support.drivervehicleassignment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_support_transport_crew_resource_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('work_date', 'id'),
                'indexes': [models.Index(fields=['crew', 'work_date'], name='support_tra_crew_id_f5df8e_idx'), models.Index(fields=['driver_vehicle_assignment', 'work_date'], name='support_tra_driver__f1e3d4_idx')],
                'constraints': [models.UniqueConstraint(fields=('crew', 'work_date'), name='support_unique_crew_resource_day')],
            },
        ),
    ]
