# Generated by Django 5.2.10 on 2026-08-11 19:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0023_add_crew_resource_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('internal_name', models.CharField(blank=True, default='', max_length=160)),
                ('state', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_first_crews', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_crews', to='support.supportorganization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_crews', to='support.workproject')),
            ],
            options={
                'ordering': ('project__internal_name', 'internal_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectCrewPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_crew_passenger_assignments', to='support.supportconnection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_crew_passengers', to=settings.AUTH_USER_MODEL)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_assignments', to='support.projectcrew')),
            ],
            options={
                'ordering': ('crew_id', 'starts_on', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectCrewResourceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_crew_resource_assignments', to=settings.AUTH_USER_MODEL)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignments', to='support.projectcrew')),
                ('driver_connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_crew_driver_assignments', to='support.supportconnection')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_crew_resource_assignments', to='support.vehicle')),
            ],
            options={
                'ordering': ('-starts_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectCrewShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('work_date', models.DateField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('break_minutes', models.PositiveSmallIntegerField(default=0)),
                ('state', models.CharField(choices=[('published', 'Published'), ('cancelled', 'Cancelled')], default='published', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_crew_shifts', to=settings.AUTH_USER_MODEL)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_shifts', to='support.projectcrew')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_crew_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('work_date', 'starts_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectCrewShiftMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('driver', 'Driver'), ('passenger', 'Passenger')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_crew_shift_memberships', to='support.supportconnection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_crew_shift_members', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='support.projectcrewshift')),
                ('vehicle', models.ForeignKey(blank=True, help_text='Required only for the driver snapshot.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_crew_shift_driver_entries', to='support.vehicle')),
            ],
            options={
                'ordering': ('shift_id', 'role', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='projectcrew',
            index=models.Index(fields=['organization', 'state'], name='support_pc_org_state_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcrew',
            index=models.Index(fields=['project', 'state'], name='support_pc_project_state_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcrewpassenger',
            index=models.Index(fields=['crew', 'starts_on'], name='support_pc_pass_crew_start_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcrewpassenger',
            index=models.Index(fields=['connection', 'starts_on'], name='support_pc_pass_worker_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectcrewpassenger',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('starts_on__lte', models.F('ends_on')), _connector='OR'), name='support_pc_passenger_valid_period'),
        ),
        migrations.AddConstraint(
            model_name='projectcrewpassenger',
            constraint=models.UniqueConstraint(condition=models.Q(('ends_on__isnull', True)), fields=('crew', 'connection'), name='support_pc_one_open_passenger'),
        ),
        migrations.AddIndex(
            model_name='projectcrewresourceassignment',
            index=models.Index(fields=['crew', 'starts_on'], name='support_pc_res_crew_start_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcrewresourceassignment',
            index=models.Index(fields=['driver_connection', 'starts_on'], name='support_pc_res_driver_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcrewresourceassignment',
            index=models.Index(fields=['vehicle', 'starts_on'], name='support_pc_res_vehicle_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectcrewresourceassignment',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('starts_on__lte', models.F('ends_on')), _connector='OR'), name='support_pc_resource_valid_period'),
        ),
        migrations.AddConstraint(
            model_name='projectcrewresourceassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ends_on__isnull', True)), fields=('crew',), name='support_pc_one_open_resource'),
        ),
        migrations.AddConstraint(
            model_name='projectcrewresourceassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ends_on__isnull', True)), fields=('driver_connection',), name='support_pc_one_open_driver'),
        ),
        migrations.AddConstraint(
            model_name='projectcrewresourceassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ends_on__isnull', True)), fields=('vehicle',), name='support_pc_one_open_vehicle'),
        ),
        migrations.AddIndex(
            model_name='projectcrewshift',
            index=models.Index(fields=['crew', 'state', 'work_date'], name='support_pc_shift_crew_day_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectcrewshift',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('ends_at'))), name='support_pc_shift_valid_period'),
        ),
        migrations.AddConstraint(
            model_name='projectcrewshift',
            constraint=models.UniqueConstraint(fields=('crew', 'work_date'), name='support_pc_one_shift_per_day'),
        ),
        migrations.AddIndex(
            model_name='projectcrewshiftmember',
            index=models.Index(fields=['connection', 'role'], name='support_pc_member_worker_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcrewshiftmember',
            index=models.Index(fields=['shift', 'role'], name='support_pc_member_shift_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectcrewshiftmember',
            constraint=models.UniqueConstraint(fields=('shift', 'connection'), name='support_pc_unique_shift_worker'),
        ),
        migrations.AddConstraint(
            model_name='projectcrewshiftmember',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'driver')), fields=('shift',), name='support_pc_one_shift_driver'),
        ),
        migrations.AddConstraint(
            model_name='projectcrewshiftmember',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'driver'), ('vehicle__isnull', False)), models.Q(('role', 'passenger'), ('vehicle__isnull', True)), _connector='OR'), name='support_pc_member_vehicle_by_role'),
        ),
    ]
