# Generated by Django 5.2.10 on 2026-08-12 18:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0025_sync_project_crew_worker_calendars"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCrewDriverSubstitution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("work_date", models.DateField()),
                ("state", models.CharField(choices=[("active", "Active"), ("replaced", "Replaced"), ("cancelled", "Cancelled")], default="active", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_project_crew_driver_substitutions", to=settings.AUTH_USER_MODEL)),
                ("crew", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="driver_substitutions", to="support.projectcrew")),
                ("ended_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ended_project_crew_driver_substitutions", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_crew_driver_substitutions", to="support.supportorganization")),
                ("primary_driver_connection", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="project_crew_primary_driver_substitutions", to="support.supportconnection")),
                ("substitute_driver_connection", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="project_crew_substitute_driver_dates", to="support.supportconnection")),
                ("vehicle", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="project_crew_driver_substitutions", to="support.vehicle")),
            ],
            options={
                "ordering": ("-work_date", "-created_at", "-id"),
                "indexes": [
                    models.Index(fields=["organization", "work_date"], name="support_pc_sub_org_day_idx"),
                    models.Index(fields=["crew", "work_date", "state"], name="support_pc_sub_crew_day_idx"),
                    models.Index(fields=["substitute_driver_connection", "work_date"], name="support_pc_sub_driver_day_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("state", "active")), fields=("crew", "work_date"), name="support_pc_one_active_substitution"),
                    models.CheckConstraint(condition=models.Q(("primary_driver_connection", models.F("substitute_driver_connection")), _negated=True), name="support_pc_substitute_diff_driver"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectCrewMemberAbsence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("work_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("connection", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="project_crew_absences", to="support.supportconnection")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_project_crew_absences", to=settings.AUTH_USER_MODEL)),
                ("crew", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="member_absences", to="support.projectcrew")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_crew_member_absences", to="support.supportorganization")),
            ],
            options={
                "ordering": ("work_date", "crew_id", "connection_id"),
                "indexes": [
                    models.Index(fields=["organization", "work_date"], name="support_pc_abs_org_day_idx"),
                    models.Index(fields=["connection", "work_date"], name="support_pc_abs_worker_day_idx"),
                    models.Index(fields=["crew", "work_date"], name="support_pc_abs_crew_day_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("crew", "connection", "work_date"), name="support_pc_unique_member_absence"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkerScheduleDayOff",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("work_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("connection", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="schedule_days_off", to="support.supportconnection")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_worker_schedule_days_off", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="worker_schedule_days_off", to="support.supportorganization")),
            ],
            options={
                "ordering": ("work_date", "connection_id"),
                "indexes": [
                    models.Index(fields=["organization", "work_date"], name="support_dayoff_org_day_idx"),
                    models.Index(fields=["connection", "work_date"], name="support_dayoff_worker_day_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("connection", "work_date"), name="support_unique_worker_day_off"),
                ],
            },
        ),
    ]
