# Generated by Django 5.2.10 on 2026-08-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0029_allow_resources_in_multiple_project_crews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdecisionevent',
            name='action',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('clarification_requested', 'Clarification requested'), ('clarification_answered', 'Clarification answered'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], max_length=32),
        ),
    ]
