# Generated by Django 5.2.10 on 2026-09-03 08:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0037_supportmessage_contact_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerrequest',
            name='request_type',
            field=models.CharField(choices=[('day_off', 'Day off'), ('vacation', 'Vacation'), ('unpaid_absence', 'Unpaid absence'), ('unable_today', 'Unable to work today'), ('extra_shift', 'Extra shifts'), ('exit_request', 'Exit request')], max_length=32),
        ),
        migrations.AlterField(
            model_name='workerrequestevent',
            name='action',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('clarification_requested', 'Clarification requested'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('extra_date_declined', 'Extra-shift date declined')], max_length=32),
        ),
        migrations.CreateModel(
            name='WorkerRequestDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('work_date', models.DateField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('assigned', 'Shift assigned'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='requested', max_length=16)),
                ('manager_note', models.CharField(blank=True, default='', max_length=500)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_support_worker_request_dates', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_shift_dates', to='support.workerrequest')),
            ],
            options={
                'ordering': ('work_date', 'id'),
                'indexes': [models.Index(fields=['request', 'status', 'work_date'], name='support_wor_request_632a2b_idx')],
                'constraints': [models.UniqueConstraint(fields=('request', 'work_date'), name='support_unique_extra_shift_request_date')],
            },
        ),
    ]
