# Generated by Django 5.2.10 on 2026-09-04 03:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0038_alter_workerrequest_request_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessage',
            name='body',
            field=models.TextField(blank=True, default='', max_length=1500),
        ),
        migrations.CreateModel(
            name='SupportChatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('object_key', models.CharField(max_length=500, unique=True)),
                ('content_type', models.CharField(max_length=40)),
                ('byte_size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('purge_after', models.DateTimeField(blank=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_chat_images', to='support.supportorganization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_support_chat_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SupportMessageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_links', to='support.supportchatimage')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_links', to='support.supportmessage')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='supportchatimage',
            index=models.Index(fields=['organization', 'created_at'], name='support_sup_organiz_5989b8_idx'),
        ),
        migrations.AddIndex(
            model_name='supportchatimage',
            index=models.Index(fields=['purge_after', 'purged_at'], name='support_sup_purge_a_f354d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportmessageimage',
            constraint=models.UniqueConstraint(fields=('message', 'image'), name='support_unique_message_chat_image'),
        ),
        migrations.AddConstraint(
            model_name='supportmessageimage',
            constraint=models.UniqueConstraint(fields=('message', 'position'), name='support_unique_message_image_position'),
        ),
    ]
