# Generated by Django 5.2.10 on 2026-09-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0039_alter_supportmessage_body_supportchatimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcrew',
            name='driver_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectcrew',
            name='driver_comment_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
