# Generated by Django 5.2.10 on 2026-09-08 18:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0040_projectcrew_driver_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='original_language',
            field=models.CharField(choices=[('auto', 'Detect automatically'), ('ru', 'Russian'), ('en', 'English'), ('pl', 'Polish'), ('uk', 'Ukrainian')], default='en', max_length=16),
        ),
        migrations.CreateModel(
            name='AnnouncementTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('target_language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('pl', 'Polish'), ('uk', 'Ukrainian')], max_length=2)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('detected_source_language', models.CharField(blank=True, default='', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=360)),
                ('body', models.TextField(blank=True, default='', max_length=12000)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('provider_version', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('failed', 'Failed')], max_length=16)),
                ('error_code', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_cache', to='support.announcement')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_announcement_translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('announcement', 'target_language'), name='support_unique_announcement_translation_language')],
            },
        ),
    ]
