# Generated from mobile/lib/data/city_catalog.dart for the employer web form.
CITY_CATALOG = {
    'AD': [
        'Andorra la Vella',
        'Escaldes-Engordany',
        'Encamp',
        'Sant Julia de Loria',
        'La Massana',
        'Ordino',
        'Canillo',
    ],
    'AE': [
        'Dubai',
        'Abu Dhabi',
        'Sharjah',
        'Ajman',
        'Ras Al Khaimah',
        'Fujairah',
        'Umm Al Quwain',
        'Al Ain',
        'Khor Fakkan',
        'Dibba Al-Fujairah',
        'Jebel Ali',
        'Ruwais',
        'Ghayathi',
        'Madinat Zayed',
        'Liwa',
        'Hatta',
        'Kalba',
        'Dhaid',
        'Masfout',
        'Al Madam',
    ],
    'AL': [
        'Tirana',
        'Durres',
        'Vlore',
        'Elbasan',
        'Shkoder',
        'Fier',
        'Korce',
        'Berat',
        'Lushnje',
        'Kavaje',
        'Gjirokaster',
        'Sarande',
        'Lezhe',
        'Kukes',
        'Pogradec',
        'Kruje',
        'Patos',
        'Lac',
        'Burrel',
        'Permet',
    ],
    'AM': [
        'Yerevan',
        'Gyumri',
        'Vanadzor',
        'Vagharshapat',
        'Abovyan',
        'Kapan',
        'Hrazdan',
        'Armavir',
        'Artashat',
        'Ijevan',
        'Goris',
        'Charentsavan',
        'Ararat',
        'Masis',
        'Sevan',
        'Ashtarak',
        'Dilijan',
        'Alaverdi',
        'Martuni',
        'Vardenis',
    ],
    'AT': [
        'Vienna',
        'Graz',
        'Linz',
        'Salzburg',
        'Innsbruck',
        'Klagenfurt',
        'Villach',
        'Wels',
        'St. Polten',
        'Dornbirn',
        'Wiener Neustadt',
        'Steyr',
        'Feldkirch',
        'Bregenz',
        'Leonding',
        'Klosterneuburg',
        'Baden',
        'Wolfsberg',
        'Leoben',
        'Krems',
        'Traun',
        'Amstetten',
        'Lustenau',
        'Kapfenberg',
        'Modling',
        'Hallein',
        'Kufstein',
        'Traiskirchen',
        'Schwechat',
        'Braunau am Inn',
        'Stockerau',
        'Saalfelden',
        'Tulln',
        'Hohenems',
        'Spittal an der Drau',
        'Ternitz',
        'Perchtoldsdorf',
        'Feldkirchen in Karnten',
        'Deutschlandsberg',
        'Bad Ischl',
        'Gmunden',
        'Bruck an der Mur',
        'Bludenz',
        'Korneuburg',
        'Hollabrunn',
        'Zwettl',
        'Rust',
        'Waidhofen an der Ybbs',
        'Judenburg',
        'Schwaz',
    ],
    'AU': [
        'Sydney',
        'Melbourne',
        'Brisbane',
        'Perth',
        'Adelaide',
        'Gold Coast',
        'Canberra',
        'Newcastle',
        'Wollongong',
        'Geelong',
        'Hobart',
        'Townsville',
        'Cairns',
        'Darwin',
        'Toowoomba',
        'Ballarat',
        'Bendigo',
        'Albury',
        'Launceston',
        'Mackay',
        'Rockhampton',
        'Bunbury',
        'Bundaberg',
        'Coffs Harbour',
        'Wagga Wagga',
        'Shepparton',
        'Mildura',
        'Gladstone',
        'Tamworth',
        'Orange',
    ],
    'AZ': [
        'Baku',
        'Ganja',
        'Sumqayit',
        'Mingachevir',
        'Lankaran',
        'Shirvan',
        'Nakhchivan',
        'Shaki',
        'Yevlakh',
        'Khirdalan',
        'Barda',
        'Goychay',
        'Quba',
        'Zaqatala',
        'Salyan',
        'Agdash',
        'Shamkir',
        'Tovuz',
        'Sabirabad',
        'Masalli',
    ],
    'BA': [
        'Sarajevo',
        'Banja Luka',
        'Tuzla',
        'Zenica',
        'Mostar',
        'Bijeljina',
        'Prijedor',
        'Brcko',
        'Doboj',
        'Cazin',
        'Zvornik',
        'Zivinice',
        'Gradiska',
        'Teslic',
        'Travnik',
        'Bihac',
        'Lukavac',
        'Trebinje',
        'Visoko',
        'Gorazde',
    ],
    'BE': [
        'Brussels',
        'Antwerp',
        'Ghent',
        'Charleroi',
        'Liege',
        'Bruges',
        'Namur',
        'Leuven',
        'Mons',
        'Aalst',
        'Mechelen',
        'La Louviere',
        'Kortrijk',
        'Hasselt',
        'Sint-Niklaas',
        'Ostend',
        'Genk',
        'Seraing',
        'Roeselare',
        'Mouscron',
        'Verviers',
        'Dendermonde',
        'Beringen',
        'Turnhout',
        'Vilvoorde',
        'Sint-Truiden',
        'Lokeren',
        'Eupen',
        'Tournai',
        'Ieper',
        'Herstal',
        'Ninove',
        'Eeklo',
        'Geraardsbergen',
        'Diest',
        'Knokke-Heist',
        'Waregem',
        'Spa',
        'Malmedy',
        'Tongeren',
        'Arlon',
        'Wavre',
        'Waterloo',
        'Heist-op-den-Berg',
        'Lier',
        'Oudenaarde',
        'Lommel',
        'Halle',
        'Geel',
        'Ronse',
    ],
    'BG': [
        'Sofia',
        'Plovdiv',
        'Varna',
        'Burgas',
        'Ruse',
        'Stara Zagora',
        'Pleven',
        'Sliven',
        'Dobrich',
        'Shumen',
        'Pernik',
        'Haskovo',
        'Yambol',
        'Pazardzhik',
        'Blagoevgrad',
        'Veliko Tarnovo',
        'Vratsa',
        'Gabrovo',
        'Asenovgrad',
        'Vidin',
        'Kazanlak',
        'Kyustendil',
        'Kardzhali',
        'Montana',
        'Dimitrovgrad',
        'Targovishte',
        'Lovech',
        'Silistra',
        'Dupnitsa',
        'Razgrad',
        'Svishtov',
        'Smolyan',
        'Petrich',
        'Samokov',
        'Lom',
        'Sevlievo',
        'Nova Zagora',
        'Velingrad',
        'Sandanski',
        'Troyan',
        'Karlovo',
        'Provadia',
        'Pomorie',
        'Botevgrad',
        'Gotse Delchev',
        'Aytos',
        'Parvomay',
        'Popovo',
        'Chirpan',
        'Radomir',
    ],
    'CA': [
        'Toronto',
        'Montreal',
        'Calgary',
        'Ottawa',
        'Edmonton',
        'Winnipeg',
        'Mississauga',
        'Vancouver',
        'Brampton',
        'Hamilton',
        'Quebec City',
        'Surrey',
        'Laval',
        'Halifax',
        'London',
        'Markham',
        'Vaughan',
        'Gatineau',
        'Saskatoon',
        'Longueuil',
        'Kitchener',
        'Burnaby',
        'Windsor',
        'Regina',
        'Richmond',
        'Oakville',
        'Burlington',
        'Greater Sudbury',
        'Sherbrooke',
        'Saguenay',
        'St. Catharines',
        'Oshawa',
        'Levis',
        'Barrie',
        'Abbotsford',
        'Coquitlam',
        'Trois-Rivieres',
        'Kingston',
        'Guelph',
        'Cambridge',
        'Whitby',
        'Kelowna',
        'Langley',
        'Ajax',
        'Thunder Bay',
        'Terrebonne',
        'Milton',
        'Nanaimo',
        'Moncton',
        'Chilliwack',
    ],
    'CH': [
        'Zurich',
        'Geneva',
        'Basel',
        'Lausanne',
        'Bern',
        'Winterthur',
        'Lucerne',
        'St. Gallen',
        'Lugano',
        'Biel/Bienne',
        'Thun',
        'Koniz',
        'La Chaux-de-Fonds',
        'Fribourg',
        'Schaffhausen',
        'Chur',
        'Vernier',
        'Neuchatel',
        'Uster',
        'Sion',
        'Zug',
        'Yverdon-les-Bains',
        'Montreux',
        'Frauenfeld',
        'Wil',
        'Rapperswil-Jona',
        'Baden',
        'Vevey',
        'Bellinzona',
        'Aarau',
        'Emmen',
        'Kriens',
        'Dietikon',
        'Wetzikon',
        'Horgen',
        'Duebendorf',
        'Kreuzlingen',
        'Olten',
        'Nyon',
        'Renens',
    ],
    'CY': [
        'Nicosia',
        'Limassol',
        'Larnaca',
        'Famagusta',
        'Paphos',
        'Kyrenia',
        'Strovolos',
        'Paralimni',
        'Aglantzia',
        'Aradippou',
        'Lakatamia',
        'Geroskipou',
        'Dali',
        'Ayia Napa',
        'Protaras',
        'Polis',
        'Livadia',
        'Ypsonas',
        'Kolossi',
        'Athienou',
        'Dherynia',
        'Sotira',
        'Xylofagou',
        'Frenaros',
        'Pera Chorio',
        'Psimolofou',
        'Oroklini',
        'Tseri',
        'Kato Polemidia',
        'Mesa Geitonia',
        'Zakaki',
        'Chloraka',
        'Emba',
        'Tala',
        'Peyia',
        'Yeri',
        'Kiti',
        'Pervolia',
        'Lefkara',
        'Kakopetria',
        'Lapithos',
        'Lefkoniko',
        'Rizokarpaso',
        'Morphou',
        'Latsia',
        'Kaimakli',
        'Engomi',
        'Lakatameia',
        'Dasoupoli',
        'Agros',
    ],
    'CZ': [
        'Prague',
        'Brno',
        'Ostrava',
        'Plzen',
        'Liberec',
        'Olomouc',
        'Ceske Budejovice',
        'Hradec Kralove',
        'Usti nad Labem',
        'Pardubice',
        'Zlin',
        'Havirov',
        'Kladno',
        'Most',
        'Opava',
        'Frydek-Mistek',
        'Jihlava',
        'Karlovy Vary',
        'Teplice',
        'Decin',
        'Chomutov',
        'Karvina',
        'Jablonec nad Nisou',
        'Prostejov',
        'Prerov',
        'Mlada Boleslav',
        'Ceska Lipa',
        'Trebic',
        'Trinec',
        'Tabor',
        'Znojmo',
        'Pribram',
        'Kolin',
        'Pisek',
        'Vsetin',
        'Uherske Hradiste',
        'Kromeriz',
        'Cheb',
        'Sokolov',
        'Sumperk',
        'Hodonin',
        'Breclav',
        'Orlova',
        'Havlickuv Brod',
        'Trutnov',
        'Litomerice',
        'Chrudim',
        'Vyskov',
        'Blansko',
        'Bohumin',
    ],
    'DE': [
        'Berlin',
        'Hamburg',
        'Munich',
        'Cologne',
        'Frankfurt',
        'Stuttgart',
        'Dusseldorf',
        'Dortmund',
        'Essen',
        'Leipzig',
        'Bremen',
        'Dresden',
        'Hanover',
        'Nuremberg',
        'Duisburg',
        'Bochum',
        'Wuppertal',
        'Bielefeld',
        'Bonn',
        'Munster',
        'Karlsruhe',
        'Mannheim',
        'Augsburg',
        'Wiesbaden',
        'Gelsenkirchen',
        'Monchengladbach',
        'Braunschweig',
        'Chemnitz',
        'Kiel',
        'Aachen',
        'Halle',
        'Magdeburg',
        'Freiburg',
        'Krefeld',
        'Lubeck',
        'Oberhausen',
        'Erfurt',
        'Mainz',
        'Rostock',
        'Kassel',
        'Hagen',
        'Hamm',
        'Saarbrucken',
        'Mulheim an der Ruhr',
        'Potsdam',
        'Ludwigshafen',
        'Leverkusen',
        'Oldenburg',
        'Osnabruck',
        'Solingen',
    ],
    'DK': [
        'Copenhagen',
        'Aarhus',
        'Odense',
        'Aalborg',
        'Esbjerg',
        'Randers',
        'Kolding',
        'Horsens',
        'Vejle',
        'Roskilde',
        'Herning',
        'Hjorring',
        'Silkeborg',
        'Naestved',
        'Fredericia',
        'Viborg',
        'Koge',
        'Holstebro',
        'Slagelse',
        'Taastrup',
        'Svendborg',
        'Sonderborg',
        'Holbaek',
        'Hillerod',
        'Frederikshavn',
        'Haderslev',
        'Ringsted',
        'Skive',
        'Birkerod',
        'Farum',
        'Nyborg',
        'Middelfart',
        'Kalundborg',
        'Grenaa',
        'Frederikssund',
        'Aabenraa',
        'Dragor',
        'Odder',
        'Korsor',
        'Helsinge',
        'Hobro',
        'Thisted',
        'Varde',
        'Ribe',
        'Ebeltoft',
        'Bronderslev',
        'Vordingborg',
        'Nakskov',
        'Ronne',
        'Maribo',
    ],
    'EE': [
        'Tallinn',
        'Tartu',
        'Narva',
        'Parnu',
        'Kohtla-Jarve',
        'Viljandi',
        'Rakvere',
        'Maardu',
        'Kuressaare',
        'Sillamae',
        'Valga',
        'Voru',
        'Haapsalu',
        'Keila',
        'Paide',
        'Jogeva',
        'Tapa',
        'Turi',
        'Rapla',
        'Elva',
        'Saue',
        'Kohila',
        'Johvi',
        'Kivioli',
        'Poltsamaa',
        'Paldiski',
        'Tamsalu',
        'Kunda',
        'Otepaa',
        'Kardla',
        'Loksa',
        'Vohma',
        'Sindi',
        'Polva',
        'Torva',
        'Kilingi-Nomme',
        'Mustvee',
        'Narva-Joesuu',
        'Antsla',
        'Rapina',
        'Lihula',
        'Parnu-Jaagupi',
        'Tabasalu',
        'Kohtla-Nomme',
        'Abja-Paluoja',
        'Kehra',
        'Juri',
        'Kiili',
        'Toila',
        'Vandra',
    ],
    'ES': [
        'Madrid',
        'Barcelona',
        'Valencia',
        'Seville',
        'Zaragoza',
        'Malaga',
        'Murcia',
        'Palma',
        'Bilbao',
        'Alicante',
        'Cordoba',
        'Valladolid',
        'Vigo',
        'Gijon',
        'LHospitalet de Llobregat',
        'A Coruna',
        'Vitoria-Gasteiz',
        'Granada',
        'Elche',
        'Oviedo',
        'Badalona',
        'Cartagena',
        'Terrassa',
        'Jerez de la Frontera',
        'Sabadell',
        'Mostoles',
        'Santa Cruz de Tenerife',
        'Pamplona',
        'Almeria',
        'Alcala de Henares',
        'Fuenlabrada',
        'Leganes',
        'Santander',
        'Castellon de la Plana',
        'Burgos',
        'Albacete',
        'Alcorcon',
        'Getafe',
        'Salamanca',
        'Logrono',
        'Badajoz',
        'Huelva',
        'Lleida',
        'Tarragona',
        'Leon',
        'Cadiz',
        'Marbella',
        'Dos Hermanas',
        'Jaen',
        'Ourense',
    ],
    'FI': [
        'Helsinki',
        'Espoo',
        'Tampere',
        'Vantaa',
        'Oulu',
        'Turku',
        'Jyvaskyla',
        'Lahti',
        'Kuopio',
        'Pori',
        'Kouvola',
        'Joensuu',
        'Lappeenranta',
        'Hameenlinna',
        'Vaasa',
        'Seinajoki',
        'Rovaniemi',
        'Mikkeli',
        'Kotka',
        'Salo',
        'Porvoo',
        'Kokkola',
        'Hyvinkaa',
        'Jarvenpaa',
        'Lohja',
        'Nurmijarvi',
        'Kirkkonummi',
        'Tuusula',
        'Kerava',
        'Kajaani',
        'Rauma',
        'Savonlinna',
        'Kaarina',
        'Nokia',
        'Ylojarvi',
        'Riihimaki',
        'Imatra',
        'Raahe',
        'Raisio',
        'Hollola',
        'Sipoo',
        'Lieto',
        'Kangasala',
        'Tornio',
        'Kempele',
        'Pirkkala',
        'Mustasaari',
        'Vihti',
        'Jakobstad',
        'Forssa',
    ],
    'FR': [
        'Paris',
        'Marseille',
        'Lyon',
        'Toulouse',
        'Nice',
        'Nantes',
        'Strasbourg',
        'Montpellier',
        'Bordeaux',
        'Lille',
        'Rennes',
        'Reims',
        'Saint-Etienne',
        'Toulon',
        'Le Havre',
        'Grenoble',
        'Dijon',
        'Angers',
        'Nimes',
        'Villeurbanne',
        'Clermont-Ferrand',
        'Le Mans',
        'Aix-en-Provence',
        'Brest',
        'Tours',
        'Amiens',
        'Limoges',
        'Annecy',
        'Perpignan',
        'Metz',
        'Besancon',
        'Orleans',
        'Mulhouse',
        'Rouen',
        'Caen',
        'Nancy',
        'Saint-Denis',
        'Argenteuil',
        'Montreuil',
        'Roubaix',
        'Avignon',
        'Tourcoing',
        'Poitiers',
        'Dunkirk',
        'Nanterre',
        'Courbevoie',
        'Versailles',
        'Pau',
        'La Rochelle',
        'Bourges',
    ],
    'GE': [
        'Tbilisi',
        'Batumi',
        'Kutaisi',
        'Rustavi',
        'Gori',
        'Zugdidi',
        'Poti',
        'Kobuleti',
        'Khashuri',
        'Samtredia',
        'Senaki',
        'Zestafoni',
        'Marneuli',
        'Telavi',
        'Akhaltsikhe',
        'Ozurgeti',
        'Kaspi',
        'Chiatura',
        'Borjomi',
        'Mtskheta',
    ],
    'GR': [
        'Athens',
        'Thessaloniki',
        'Patras',
        'Heraklion',
        'Larissa',
        'Volos',
        'Rhodes',
        'Ioannina',
        'Chania',
        'Agrinio',
        'Kalamata',
        'Katerini',
        'Serres',
        'Xanthi',
        'Kavala',
        'Trikala',
        'Lamia',
        'Alexandroupoli',
        'Kozani',
        'Veria',
        'Drama',
        'Komotini',
        'Chalcis',
        'Karditsa',
        'Rethymno',
        'Corinth',
        'Sparta',
        'Mytilene',
        'Kos',
        'Corfu',
        'Ptolemaida',
        'Tripoli',
        'Preveza',
        'Pyrgos',
        'Naousa',
        'Orestiada',
        'Florina',
        'Arta',
        'Livadeia',
        'Argos',
        'Giannitsa',
        'Elefsina',
        'Megara',
        'Thiva',
        'Missolonghi',
        'Kilkis',
        'Edessa',
        'Zakynthos',
        'Chios',
        'Samos',
    ],
    'HR': [
        'Zagreb',
        'Split',
        'Rijeka',
        'Osijek',
        'Zadar',
        'Slavonski Brod',
        'Pula',
        'Karlovac',
        'Sisak',
        'Varazdin',
        'Dubrovnik',
        'Samobor',
        'Velika Gorica',
        'Bjelovar',
        'Vinkovci',
        'Solin',
        'Koprivnica',
        'Dakovo',
        'Pozega',
        'Metkovic',
        'Cakovec',
        'Virovitica',
        'Krizevci',
        'Zapresic',
        'Rovinj',
        'Makarska',
        'Trogir',
        'Knin',
        'Opatija',
        'Petrinja',
        'Kutina',
        'Nasice',
        'Beli Manastir',
        'Dugo Selo',
        'Sinj',
        'Imotski',
        'Porec',
        'Umag',
        'Novalja',
        'Crikvenica',
        'Kastela',
        'Ivanic-Grad',
        'Ogulin',
        'Vukovar',
        'Nova Gradiska',
        'Krapina',
        'Pazin',
        'Labin',
        'Gospic',
        'Buzet',
    ],
    'HU': [
        'Budapest',
        'Debrecen',
        'Szeged',
        'Miskolc',
        'Pecs',
        'Gyor',
        'Nyiregyhaza',
        'Kecskemet',
        'Szekesfehervar',
        'Szombathely',
        'Szolnok',
        'Tatabanya',
        'Kaposvar',
        'Bekescsaba',
        'Erd',
        'Zalaegerszeg',
        'Veszprem',
        'Eger',
        'Nagykanizsa',
        'Dunaujvaros',
        'Hodmezovasarhely',
        'Sopron',
        'Cegled',
        'Salgotarjan',
        'Baja',
        'Ajka',
        'Oroshaza',
        'Karcag',
        'Siofok',
        'Godollo',
        'Mosonmagyarovar',
        'Gyongyos',
        'Kazincbarcika',
        'Vac',
        'Szekszard',
        'Papa',
        'Hatvan',
        'Monor',
        'Esztergom',
        'Gyula',
        'Mako',
        'Komlo',
        'Budaors',
        'Veresegyhaz',
        'Tiszaujvaros',
        'Kiskunhalas',
        'Csongrad',
        'Sarvar',
        'Szarvas',
        'Hajduszoboszlo',
    ],
    'IE': [
        'Dublin',
        'Cork',
        'Limerick',
        'Galway',
        'Waterford',
        'Drogheda',
        'Dundalk',
        'Swords',
        'Bray',
        'Navan',
        'Kilkenny',
        'Ennis',
        'Carlow',
        'Tralee',
        'Newbridge',
        'Portlaoise',
        'Celbridge',
        'Mullingar',
        'Wexford',
        'Letterkenny',
        'Athlone',
        'Sligo',
        'Cavan',
        'Clonmel',
        'Balbriggan',
        'Tullamore',
        'Killarney',
        'Arklow',
        'Midleton',
        'Maynooth',
        'Mallow',
        'Malahide',
        'Naas',
        'Greystones',
        'Longford',
        'Castlebar',
        'Thurles',
        'Tuam',
        'Ballina',
        'Trim',
        'Roscommon',
        'Nenagh',
        'Carrigaline',
        'Shannon',
        'Gorey',
        'Passage West',
        'Bandon',
        'Monaghan',
        'Wicklow',
        'Kinsale',
    ],
    'IL': [
        'Jerusalem',
        'Tel Aviv',
        'Haifa',
        'Rishon LeZion',
        'Petah Tikva',
        'Ashdod',
        'Netanya',
        'Beersheba',
        'Bnei Brak',
        'Holon',
        'Ramat Gan',
        'Ashkelon',
        'Rehovot',
        'Bat Yam',
        'Kfar Saba',
        'Herzliya',
        'Hadera',
        'Modiin-Maccabim-Reut',
        'Nazareth',
        'Lod',
        'Ramla',
        'Raanana',
        'Givatayim',
        'Eilat',
        'Acre',
    ],
    'IS': [
        'Reykjavik',
        'Kopavogur',
        'Hafnarfjordur',
        'Akureyri',
        'Reykjanesbaer',
        'Gardabaer',
        'Mosfellsbaer',
        'Selfoss',
        'Akranes',
        'Seltjarnarnes',
        'Vestmannaeyjar',
        'Egilsstadir',
    ],
    'IT': [
        'Rome',
        'Milan',
        'Naples',
        'Turin',
        'Palermo',
        'Genoa',
        'Bologna',
        'Florence',
        'Bari',
        'Catania',
        'Venice',
        'Verona',
        'Messina',
        'Padua',
        'Trieste',
        'Taranto',
        'Brescia',
        'Parma',
        'Prato',
        'Modena',
        'Reggio Calabria',
        'Reggio Emilia',
        'Perugia',
        'Livorno',
        'Ravenna',
        'Cagliari',
        'Foggia',
        'Rimini',
        'Salerno',
        'Ferrara',
        'Sassari',
        'Latina',
        'Giugliano in Campania',
        'Monza',
        'Siracusa',
        'Pescara',
        'Bergamo',
        'Forli',
        'Trento',
        'Vicenza',
        'Terni',
        'Bolzano',
        'Novara',
        'Piacenza',
        'Ancona',
        'Andria',
        'Arezzo',
        'Udine',
        'Cesena',
        'Lecce',
    ],
    'KG': [
        'Bishkek',
        'Osh',
        'Jalal-Abad',
        'Karakol',
        'Tokmok',
        'Uzgen',
        'Balykchy',
        'Kara-Balta',
        'Naryn',
        'Talas',
        'Batken',
        'Kyzyl-Kiya',
        'Kant',
        'Cholpon-Ata',
        'Isfana',
        'Kochkor-Ata',
        'Mailuu-Suu',
        'Kerben',
        'Shopokov',
        'Kadamjay',
    ],
    'KR': [
        'Seoul',
        'Busan',
        'Incheon',
        'Daegu',
        'Daejeon',
        'Gwangju',
        'Suwon',
        'Ulsan',
        'Changwon',
        'Goyang',
        'Yongin',
        'Seongnam',
        'Cheongju',
        'Jeonju',
        'Cheonan',
        'Ansan',
        'Anyang',
        'Pohang',
        'Gimhae',
        'Pyeongtaek',
        'Jeju City',
        'Uijeongbu',
        'Gumi',
        'Siheung',
        'Hwaseong',
        'Namyangju',
        'Gimpo',
        'Jinju',
        'Asan',
        'Wonju',
    ],
    'KZ': [
        'Almaty',
        'Astana',
        'Shymkent',
        'Karaganda',
        'Aktobe',
        'Taraz',
        'Pavlodar',
        'Oskemen',
        'Semey',
        'Atyrau',
        'Kostanay',
        'Kyzylorda',
        'Oral',
        'Petropavl',
        'Aktau',
        'Temirtau',
        'Turkistan',
        'Kokshetau',
        'Taldykorgan',
        'Ekibastuz',
        'Rudny',
        'Zhanaozen',
        'Balkhash',
        'Kentau',
        'Ridder',
        'Satpayev',
        'Stepnogorsk',
        'Aksu',
        'Arys',
        'Kapchagay',
    ],
    'LI': [
        'Vaduz',
        'Schaan',
        'Triesen',
        'Balzers',
        'Eschen',
        'Mauren',
        'Triesenberg',
        'Ruggell',
    ],
    'LT': [
        'Vilnius',
        'Kaunas',
        'Klaipeda',
        'Siauliai',
        'Panevezys',
        'Alytus',
        'Marijampole',
        'Mazeikiai',
        'Jonava',
        'Utena',
        'Kedainiai',
        'Telsiai',
        'Visaginas',
        'Taurage',
        'Ukmerge',
        'Plunge',
        'Kretinga',
        'Palanga',
        'Radviliskis',
        'Druskininkai',
        'Vilkaviskis',
        'Rokiskis',
        'Gargzdai',
        'Elektrenai',
        'Birzai',
        'Kursenai',
        'Jurbarkas',
        'Garliava',
        'Lentvaris',
        'Raseiniai',
        'Grigiskes',
        'Prienai',
        'Anyksciai',
        'Naujoji Akmene',
        'Kelme',
        'Varena',
        'Kaisiadorys',
        'Pasvalys',
        'Zarasai',
        'Sventoji',
        'Moletai',
        'Silute',
        'Trakai',
        'Neringa',
        'Kalvarija',
        'Joniskis',
        'Kupiskis',
        'Skuodas',
        'Sakiai',
        'Lazdijai',
    ],
    'LU': [
        'Luxembourg',
        'Esch-sur-Alzette',
        'Differdange',
        'Dudelange',
        'Ettelbruck',
        'Diekirch',
        'Wiltz',
        'Rumelange',
        'Echternach',
        'Grevenmacher',
        'Bettembourg',
        'Bertrange',
        'Remich',
        'Strassen',
        'Mamer',
        'Schifflange',
        'Kayl',
        'Petange',
        'Steinfort',
        'Capellen',
        'Hesperange',
        'Sandweiler',
        'Junglinster',
        'Mondorf-les-Bains',
        'Contern',
        'Roeser',
        'Kehlen',
        'Larochette',
        'Vianden',
        'Clervaux',
        'Troisvierges',
        'Redange-sur-Attert',
        'Wasserbillig',
        'Mertert',
        'Howald',
        'Soleuvre',
        'Canach',
        'Hosingen',
        'Mersch',
        'Walferdange',
        'Bascharage',
        'Belvaux',
        'Rodange',
        'Bissen',
        'Schengen',
        'Aspelt',
        'Beaufort',
        'Consdorf',
        'Dippach',
        'Lorentzweiler',
    ],
    'LV': [
        'Riga',
        'Daugavpils',
        'Liepaja',
        'Jelgava',
        'Jurmala',
        'Ventspils',
        'Rezekne',
        'Valmiera',
        'Ogre',
        'Jekabpils',
        'Cesis',
        'Tukums',
        'Salaspils',
        'Kuldiga',
        'Saldus',
        'Talsi',
        'Sigulda',
        'Dobele',
        'Bauska',
        'Limbazi',
        'Kraslava',
        'Madona',
        'Gulbene',
        'Ludza',
        'Preili',
        'Balvi',
        'Aluksne',
        'Smiltene',
        'Aizkraukle',
        'Valka',
        'Livani',
        'Olaine',
        'Saulkrasti',
        'Salacgriva',
        'Aizpute',
        'Kandava',
        'Ikskile',
        'Koknese',
        'Cibla',
        'Broceni',
        'Cesvaine',
        'Skrunda',
        'Dagda',
        'Pavilosta',
        'Akniste',
        'Kegums',
        'Lielvarde',
        'Plavinas',
        'Karsava',
        'Viesite',
    ],
    'MC': [
        'Monaco',
        'Monte Carlo',
        'La Condamine',
    ],
    'MD': [
        'Chisinau',
        'Balti',
        'Tiraspol',
        'Bender',
        'Ribnita',
        'Cahul',
        'Ungheni',
        'Soroca',
        'Orhei',
        'Dubasari',
        'Comrat',
        'Ceadir-Lunga',
        'Straseni',
        'Drochia',
        'Edinet',
        'Causeni',
        'Hincesti',
        'Ialoveni',
        'Falesti',
        'Floresti',
    ],
    'ME': [
        'Podgorica',
        'Niksic',
        'Herceg Novi',
        'Pljevlja',
        'Bijelo Polje',
        'Cetinje',
        'Bar',
        'Budva',
        'Berane',
        'Ulcinj',
        'Tivat',
        'Rozaje',
        'Kotor',
        'Danilovgrad',
        'Mojkovac',
    ],
    'MK': [
        'Skopje',
        'Bitola',
        'Kumanovo',
        'Prilep',
        'Tetovo',
        'Veles',
        'Ohrid',
        'Gostivar',
        'Strumica',
        'Kavadarci',
        'Stip',
        'Kocani',
        'Kicevo',
        'Struga',
        'Radovis',
        'Gevgelija',
        'Debar',
        'Kriva Palanka',
    ],
    'MT': [
        'Valletta',
        'Birkirkara',
        'Mosta',
        'Qormi',
        'Sliema',
        'Zabbar',
        'St. Pauls Bay',
        'Fgura',
        'Zejtun',
        'Rabat',
        'San Gwann',
        'Marsaskala',
        'Qawra',
        'Hamrun',
        'Naxxar',
        'Paola',
        'Gzira',
        'Santa Venera',
        'Mellieha',
        'Mgarr',
        'Marsa',
        'Tarxien',
        'Birzebbuga',
        'Balzan',
        'Siggiewi',
        'Luqa',
        'Nadur',
        'Qrendi',
        'Xaghra',
        'Zebbug',
        'Xewkija',
        'Dingli',
        'Zurrieq',
        'Sannat',
        'Fontana',
        'Kalkara',
        'Ghaxaq',
        'Gharghur',
        'Gudja',
        'Iklin',
        'Kirkop',
        'Lija',
        'Msida',
        'Pembroke',
        'Swieqi',
        'Floriana',
        'Senglea',
        'Cospicua',
        'Vittoriosa',
        'Marsaxlokk',
    ],
    'NL': [
        'Amsterdam',
        'Rotterdam',
        'The Hague',
        'Utrecht',
        'Eindhoven',
        'Tilburg',
        'Groningen',
        'Almere',
        'Breda',
        'Nijmegen',
        'Enschede',
        'Haarlem',
        'Arnhem',
        'Zaanstad',
        'Amersfoort',
        'Apeldoorn',
        'Hoofddorp',
        'Maastricht',
        'Leiden',
        'Dordrecht',
        'Zoetermeer',
        'Zwolle',
        'Deventer',
        'Delft',
        'Alkmaar',
        'Heerlen',
        'Venlo',
        'Leeuwarden',
        'Hilversum',
        'Hengelo',
        'Amstelveen',
        'Purmerend',
        'Oss',
        'Schiedam',
        'Spijkenisse',
        'Helmond',
        'Vlaardingen',
        'Gouda',
        'Alphen aan den Rijn',
        'Lelystad',
        'Hoorn',
        'Roosendaal',
        'Velsen',
        'Assen',
        'Capelle aan den IJssel',
        'Nieuwegein',
        'Katwijk',
        'Middelburg',
        'Emmen',
        'Bergen op Zoom',
    ],
    'NO': [
        'Oslo',
        'Bergen',
        'Trondheim',
        'Stavanger',
        'Drammen',
        'Fredrikstad',
        'Kristiansand',
        'Sandnes',
        'Tromso',
        'Sarpsborg',
        'Skien',
        'Alesund',
        'Sandefjord',
        'Haugesund',
        'Tonsberg',
        'Moss',
        'Porsgrunn',
        'Bodo',
        'Arendal',
        'Hamar',
        'Larvik',
        'Halden',
        'Lillehammer',
        'Molde',
        'Harstad',
        'Kristiansund',
        'Gjovik',
        'Narvik',
        'Askoy',
        'Kongsberg',
        'Alta',
        'Elverum',
        'Steinkjer',
        'Sortland',
        'Egersund',
        'Notodden',
        'Grimstad',
        'Namsos',
        'Voss',
        'Forde',
    ],
    'NZ': [
        'Auckland',
        'Wellington',
        'Christchurch',
        'Hamilton',
        'Tauranga',
        'Dunedin',
        'Palmerston North',
        'Napier',
        'Hastings',
        'Nelson',
        'Rotorua',
        'New Plymouth',
        'Whangarei',
        'Invercargill',
        'Whanganui',
        'Gisborne',
        'Timaru',
        'Blenheim',
        'Taupo',
        'Queenstown',
    ],
    'PL': [
        'Warsaw',
        'Krakow',
        'Wroclaw',
        'Lodz',
        'Poznan',
        'Gdansk',
        'Szczecin',
        'Bydgoszcz',
        'Lublin',
        'Katowice',
        'Bialystok',
        'Gdynia',
        'Czestochowa',
        'Radom',
        'Sosnowiec',
        'Torun',
        'Kielce',
        'Rzeszow',
        'Gliwice',
        'Zabrze',
        'Olsztyn',
        'Bielsko-Biala',
        'Bytom',
        'Zielona Gora',
        'Rybnik',
        'Ruda Slaska',
        'Tychy',
        'Gorzow Wielkopolski',
        'Dabrowa Gornicza',
        'Plock',
        'Elblag',
        'Opole',
        'Walbrzych',
        'Wloclawek',
        'Tarnow',
        'Chorzow',
        'Koszalin',
        'Kalisz',
        'Legnica',
        'Grudziadz',
        'Jaworzno',
        'Slupsk',
        'Jastrzebie-Zdroj',
        'Nowy Sacz',
        'Jelenia Gora',
        'Siedlce',
        'Konin',
        'Piotrkow Trybunalski',
        'Inowroclaw',
        'Lubin',
    ],
    'PT': [
        'Lisbon',
        'Porto',
        'Vila Nova de Gaia',
        'Amadora',
        'Braga',
        'Funchal',
        'Coimbra',
        'Setubal',
        'Almada',
        'Aveiro',
        'Guimaraes',
        'Leiria',
        'Faro',
        'Viseu',
        'Maia',
        'Santarem',
        'Barcelos',
        'Oeiras',
        'Cascais',
        'Matosinhos',
        'Vila Real',
        'Castelo Branco',
        'Covilha',
        'Ponta Delgada',
        'Beja',
        'Portimao',
        'Evora',
        'Torres Vedras',
        'Caldas da Rainha',
        'Seixal',
        'Gondomar',
        'Valongo',
        'Penafiel',
        'Chaves',
        'Guarda',
        'Lamego',
        'Elvas',
        'Albufeira',
        'Lagos',
        'Olhao',
        'Felgueiras',
        'Paredes',
        'Pacos de Ferreira',
        'Vila do Conde',
        'Trofa',
        'Espinho',
        'Abrantes',
        'Tomar',
        'Tavira',
        'Ponte de Lima',
    ],
    'QA': [
        'Doha',
        'Al Rayyan',
        'Al Wakrah',
        'Al Khor',
        'Umm Salal',
        'Lusail',
        'Al Daayen',
        'Mesaieed',
        'Dukhan',
        'Madinat ash Shamal',
    ],
    'RO': [
        'Bucharest',
        'Cluj-Napoca',
        'Timisoara',
        'Iasi',
        'Constanta',
        'Craiova',
        'Brasov',
        'Galati',
        'Ploiesti',
        'Oradea',
        'Braila',
        'Arad',
        'Pitesti',
        'Sibiu',
        'Bacau',
        'Targu Mures',
        'Baia Mare',
        'Buzau',
        'Botosani',
        'Satu Mare',
        'Ramnicu Valcea',
        'Suceava',
        'Piatra Neamt',
        'Drobeta-Turnu Severin',
        'Targoviste',
        'Focsani',
        'Tulcea',
        'Resita',
        'Alba Iulia',
        'Bistrita',
        'Slobozia',
        'Alexandria',
        'Zalau',
        'Vaslui',
        'Giurgiu',
        'Medias',
        'Hunedoara',
        'Deva',
        'Lugoj',
        'Roman',
        'Caracal',
        'Campina',
        'Sighetu Marmatiei',
        'Sfantu Gheorghe',
        'Turda',
        'Onesti',
        'Tecuci',
        'Mangalia',
        'Motru',
        'Petrosani',
    ],
    'RS': [
        'Belgrade',
        'Novi Sad',
        'Nis',
        'Kragujevac',
        'Subotica',
        'Zrenjanin',
        'Leskovac',
        'Pancevo',
        'Cacak',
        'Novi Pazar',
        'Kraljevo',
        'Smederevo',
        'Valjevo',
        'Krusevac',
        'Vranje',
        'Sabac',
        'Uzice',
        'Sombor',
        'Pozarevac',
        'Pirot',
        'Zajecar',
        'Kikinda',
        'Sremska Mitrovica',
        'Jagodina',
        'Bor',
    ],
    'SA': [
        'Riyadh',
        'Jeddah',
        'Mecca',
        'Medina',
        'Dammam',
        'Khobar',
        'Dhahran',
        'Taif',
        'Tabuk',
        'Buraydah',
        'Khamis Mushait',
        'Hail',
        'Hofuf',
        'Jubail',
        'Najran',
        'Abha',
        'Yanbu',
        'Al Qatif',
        'Al Kharj',
        'Sakaka',
        'Jazan',
        'Arar',
        'Al Bahah',
        'Ras Tanura',
        'Unaizah',
    ],
    'SE': [
        'Stockholm',
        'Gothenburg',
        'Malmo',
        'Uppsala',
        'Vasteras',
        'Orebro',
        'Linkoping',
        'Helsingborg',
        'Jonkoping',
        'Norrkoping',
        'Lund',
        'Umea',
        'Gavle',
        'Boras',
        'Sodertalje',
        'Eskilstuna',
        'Halmstad',
        'Vaxjo',
        'Sundsvall',
        'Lulea',
        'Trollhattan',
        'Karlstad',
        'Taby',
        'Kalmar',
        'Skovde',
        'Kristianstad',
        'Falun',
        'Karlskrona',
        'Skelleftea',
        'Uddevalla',
        'Varberg',
        'Ostersund',
        'Trelleborg',
        'Landskrona',
        'Motala',
        'Nykoping',
        'Lidkoping',
        'Pitea',
        'Visby',
        'Alingsas',
        'Katrineholm',
        'Vastervik',
        'Enkoping',
        'Sandviken',
        'Kiruna',
        'Ystad',
        'Sollentuna',
        'Huddinge',
        'Solna',
        'Varnamo',
    ],
    'SI': [
        'Ljubljana',
        'Maribor',
        'Celje',
        'Kranj',
        'Koper',
        'Velenje',
        'Novo Mesto',
        'Ptuj',
        'Trbovlje',
        'Kamnik',
        'Jesenice',
        'Nova Gorica',
        'Domzale',
        'Skofja Loka',
        'Murska Sobota',
        'Slovenj Gradec',
        'Izola',
        'Vrhnika',
        'Krsko',
        'Postojna',
        'Litija',
        'Logatec',
        'Zagorje ob Savi',
        'Slovenska Bistrica',
        'Kocevje',
        'Grosuplje',
        'Ajdovscina',
        'Idrija',
        'Brezice',
        'Ravne na Koroskem',
        'Sevnica',
        'Medvode',
        'Radovljica',
        'Tolmin',
        'Piran',
        'Lendava',
        'Ormoz',
        'Metlika',
        'Ribnica',
        'Ilirska Bistrica',
        'Cerknica',
        'Trebnje',
        'Sentjur',
        'Hrastnik',
        'Menges',
        'Prevalje',
        'Dravograd',
        'Mozirje',
        'Sezana',
        'Zalec',
    ],
    'SK': [
        'Bratislava',
        'Kosice',
        'Presov',
        'Zilina',
        'Nitra',
        'Banska Bystrica',
        'Trnava',
        'Martin',
        'Trencin',
        'Poprad',
        'Prievidza',
        'Zvolen',
        'Povazska Bystrica',
        'Michalovce',
        'Nove Zamky',
        'Spisska Nova Ves',
        'Komarno',
        'Levice',
        'Humenne',
        'Bardejov',
        'Liptovsky Mikulas',
        'Ruzomberok',
        'Piestany',
        'Lucenec',
        'Topolcany',
        'Dubnica nad Vahom',
        'Cadca',
        'Rimavska Sobota',
        'Partizanske',
        'Vranov nad Toplou',
        'Senica',
        'Hlohovec',
        'Pezinok',
        'Sala',
        'Snina',
        'Banovce nad Bebravou',
        'Handlova',
        'Malacky',
        'Skalica',
        'Svidnik',
        'Trebisov',
        'Dunajska Streda',
        'Galanta',
        'Kezmarok',
        'Detva',
        'Revuca',
        'Bytca',
        'Filakovo',
        'Modra',
        'Samorin',
    ],
    'SM': [
        'San Marino',
        'Serravalle',
        'Borgo Maggiore',
        'Domagnano',
    ],
    'TJ': [
        'Dushanbe',
        'Khujand',
        'Kulob',
        'Bokhtar',
        'Istaravshan',
        'Konibodom',
        'Isfara',
        'Panjakent',
        'Tursunzoda',
        'Vahdat',
        'Hisor',
        'Khorugh',
        'Nurek',
        'Danghara',
        'Roghun',
    ],
    'TR': [
        'Istanbul',
        'Ankara',
        'Izmir',
        'Bursa',
        'Antalya',
        'Adana',
        'Konya',
        'Gaziantep',
        'Sanliurfa',
        'Mersin',
        'Diyarbakir',
        'Kayseri',
        'Eskisehir',
        'Samsun',
        'Denizli',
        'Trabzon',
        'Malatya',
        'Erzurum',
        'Van',
        'Batman',
        'Elazig',
        'Sivas',
        'Manisa',
        'Balikesir',
        'Kahramanmaras',
        'Aydin',
        'Tekirdag',
        'Sakarya',
        'Kocaeli',
        'Mugla',
        'Mardin',
        'Hatay',
        'Afyonkarahisar',
        'Corum',
        'Isparta',
        'Edirne',
        'Rize',
        'Nevsehir',
        'Aksaray',
        'Kirikkale',
    ],
    'UA': [
        'Kyiv',
        'Kharkiv',
        'Odesa',
        'Dnipro',
        'Donetsk',
        'Zaporizhzhia',
        'Lviv',
        'Kryvyi Rih',
        'Mykolaiv',
        'Mariupol',
        'Luhansk',
        'Vinnytsia',
        'Makiivka',
        'Sevastopol',
        'Simferopol',
        'Kherson',
        'Poltava',
        'Chernihiv',
        'Cherkasy',
        'Khmelnytskyi',
        'Zhytomyr',
        'Chernivtsi',
        'Sumy',
        'Rivne',
        'Ivano-Frankivsk',
        'Ternopil',
        'Lutsk',
        'Uzhhorod',
        'Kropyvnytskyi',
        'Kamianets-Podilskyi',
        'Bila Tserkva',
        'Kremenchuk',
        'Melitopol',
        'Nikopol',
        'Brovary',
        'Mukachevo',
        'Drohobych',
        'Kolomyia',
        'Stryi',
        'Uman',
    ],
    'UK': [
        'London',
        'Birmingham',
        'Manchester',
        'Glasgow',
        'Liverpool',
        'Leeds',
        'Sheffield',
        'Edinburgh',
        'Bristol',
        'Cardiff',
        'Nottingham',
        'Newcastle upon Tyne',
        'Leicester',
        'Coventry',
        'Bradford',
        'Belfast',
        'Stoke-on-Trent',
        'Wolverhampton',
        'Plymouth',
        'Southampton',
        'Reading',
        'Derby',
        'Swansea',
        'Aberdeen',
        'Portsmouth',
        'Brighton',
        'Norwich',
        'York',
        'Oxford',
        'Cambridge',
        'Exeter',
        'Dundee',
        'Hull',
        'Sunderland',
        'Luton',
        'Milton Keynes',
        'Northampton',
        'Peterborough',
        'Bournemouth',
        'Middlesbrough',
        'Warrington',
        'Swindon',
        'Bolton',
        'Ipswich',
        'Blackpool',
        'Preston',
        'Telford',
        'Gloucester',
        'Lincoln',
    ],
    'US': [
        'New York',
        'Los Angeles',
        'Chicago',
        'Houston',
        'Phoenix',
        'Philadelphia',
        'San Antonio',
        'San Diego',
        'Dallas',
        'San Jose',
        'Austin',
        'Jacksonville',
        'Fort Worth',
        'Columbus',
        'Charlotte',
        'Indianapolis',
        'San Francisco',
        'Seattle',
        'Denver',
        'Oklahoma City',
        'Nashville',
        'El Paso',
        'Washington',
        'Boston',
        'Las Vegas',
        'Portland',
        'Detroit',
        'Louisville',
        'Memphis',
        'Baltimore',
        'Milwaukee',
        'Albuquerque',
        'Tucson',
        'Fresno',
        'Sacramento',
        'Kansas City',
        'Mesa',
        'Atlanta',
        'Omaha',
        'Colorado Springs',
        'Raleigh',
        'Miami',
        'Long Beach',
        'Virginia Beach',
        'Oakland',
        'Minneapolis',
        'Tulsa',
        'Arlington',
        'Tampa',
        'New Orleans',
    ],
    'UZ': [
        'Tashkent',
        'Samarkand',
        'Namangan',
        'Andijan',
        'Bukhara',
        'Nukus',
        'Qarshi',
        'Fergana',
        'Kokand',
        'Margilan',
        'Jizzakh',
        'Urgench',
        'Termez',
        'Navoi',
        'Angren',
        'Chirchiq',
        'Almalyk',
        'Bekabad',
        'Denov',
        'Kattakurgan',
        'Gulistan',
        'Shahrisabz',
        'Khiva',
        'Zarafshan',
        'Yangiyer',
    ],
    'XK': [
        'Pristina',
        'Prizren',
        'Ferizaj',
        'Peja',
        'Gjakova',
        'Gjilan',
        'Mitrovica',
        'Vushtrri',
        'Podujeva',
        'Suhareka',
        'Rahovec',
        'Malisheva',
    ],
}

def city_choices_for_country(country_code):
    return CITY_CATALOG.get((country_code or '').upper(), [])
