from django.urls import path
from .api import (
    AppConfigAPIView,
    VacancyListAPIView,
    VacancyDetailAPIView,
    VacancyBookmarkStatusAPIView,
    VacancyCreateAPIView,
    VacancyPendingListAPIView,
    ModerationVacancyDetailAPIView,
    VacancyApproveAPIView,
    VacancyRejectAPIView,
    VacancyResubmitAPIView,
    VacancyOwnerPauseAPIView,
    VacancyOwnerDeleteAPIView,
    VacancyMineAPIView,
    VacancyEditAPIView,
    VacancyContactAPIView,
    VacancyReviewAPIView,
    VacancyBlockOwnerAPIView,
    UserBlockListAPIView,
    UserBlockRemoveAPIView,
    VacancyUnlockRequestAPIView,
    VacancyUnlockConfirmAPIView,
    EmployerProfileAPIView,
    EmployerSubscriptionAPIView,
    EmployerSubscriptionListAPIView,
    EmployerReviewModeratorListAPIView,
    EmployerSearchAPIView,
    ComplaintAPIView,
    ComplaintByVacancyAPIView,
    ComplaintListAPIView,
    ComplaintModerationActionAPIView,
    PushDeviceAPIView,
    VacancyAlertPreviewAPIView,
    VacancyAlertSubscriptionAPIView,
    EconomyOverviewAPIView,
    ApplePurchaseCompleteAPIView,
    GooglePlayPurchaseCompleteAPIView,
    WalletTransactionListAPIView,
    VacancySubmissionStateAPIView,
    VacancyContactAccessStateAPIView,
    InternalVacancyDeleteAPIView,
    InternalVacancyImportAPIView,
)
from .auth_api import (
    RegisterAPIView,
    LoginAPIView,
    AppleLoginAPIView,
    GoogleLoginAPIView,
    VerifyEmailAPIView,
    ResendCodeAPIView,
    ResetPasswordRequestAPIView,
    ResetPasswordConfirmAPIView,
    ChangePasswordRequestAPIView,
    ChangePasswordAPIView,
    PhoneRequestCodeAPIView,
    PhoneVerifyCodeAPIView,
    MeAPIView,
    MeAvatarAPIView,
    AccountDeletionRequestAPIView,
    AccountDeletionConfirmAPIView,
    LinkEmailRequestAPIView,
    LinkEmailConfirmAPIView,
)


urlpatterns = [
    path("app/config/", AppConfigAPIView.as_view(), name="app-config"),
    path("auth/register/", RegisterAPIView.as_view(), name="api-register"),
    path("auth/login/", LoginAPIView.as_view(), name="api-login"),
    path("auth/google/", GoogleLoginAPIView.as_view(), name="api-google-login"),
    path("auth/apple/", AppleLoginAPIView.as_view(), name="api-apple-login"),
    path("auth/me/", MeAPIView.as_view(), name="api-me"),
    path("auth/me/avatar/", MeAvatarAPIView.as_view(), name="api-me-avatar"),
    path("auth/account-deletion/request/", AccountDeletionRequestAPIView.as_view(), name="api-account-deletion-request"),
    path("auth/account-deletion/confirm/", AccountDeletionConfirmAPIView.as_view(), name="api-account-deletion-confirm"),
    path("auth/verify/", VerifyEmailAPIView.as_view(), name="api-verify"),
    path("auth/resend/", ResendCodeAPIView.as_view(), name="api-resend"),
    path("auth/phone/request-code/", PhoneRequestCodeAPIView.as_view(), name="api-phone-request-code"),
    path("auth/phone/verify-code/", PhoneVerifyCodeAPIView.as_view(), name="api-phone-verify-code"),
    path("auth/link-email/request/", LinkEmailRequestAPIView.as_view(), name="api-link-email-request"),
    path("auth/link-email/confirm/", LinkEmailConfirmAPIView.as_view(), name="api-link-email-confirm"),
    path("auth/reset/request/", ResetPasswordRequestAPIView.as_view(), name="api-reset-request"),
    path("auth/reset/confirm/", ResetPasswordConfirmAPIView.as_view(), name="api-reset-confirm"),
    path("auth/password/change/request/", ChangePasswordRequestAPIView.as_view(), name="api-password-change-request"),
    path("auth/password/change/", ChangePasswordAPIView.as_view(), name="api-password-change"),
    path("notifications/devices/", PushDeviceAPIView.as_view(), name="notifications-devices"),
    path("notifications/alerts/subscription/", VacancyAlertSubscriptionAPIView.as_view(), name="notifications-alert-subscription"),
    path("notifications/alerts/preview/<int:vacancy_id>/", VacancyAlertPreviewAPIView.as_view(), name="notifications-alert-preview"),
    path("economy/overview/", EconomyOverviewAPIView.as_view(), name="economy-overview"),
    path("economy/history/", WalletTransactionListAPIView.as_view(), name="economy-history"),
    path(
        "economy/google-play/complete/",
        GooglePlayPurchaseCompleteAPIView.as_view(),
        name="economy-google-play-complete",
    ),
    path(
        "economy/apple/complete/",
        ApplePurchaseCompleteAPIView.as_view(),
        name="economy-apple-complete",
    ),
    path("economy/vacancy-submission-state/", VacancySubmissionStateAPIView.as_view(), name="economy-vacancy-submission-state"),
    path("internal/import-vacancy/", InternalVacancyImportAPIView.as_view(), name="internal-import-vacancy"),
    path("internal/delete-vacancies/", InternalVacancyDeleteAPIView.as_view(), name="internal-delete-vacancies"),

    path("vacancies/", VacancyListAPIView.as_view(), name="vacancy-list"),
    path("vacancies/bookmark-status/", VacancyBookmarkStatusAPIView.as_view(), name="vacancy-bookmark-status"),
    path("vacancies/<int:pk>/", VacancyDetailAPIView.as_view(), name="vacancy-detail"),
    path("vacancies/create/", VacancyCreateAPIView.as_view(), name="vacancy-create"),
    path("vacancies/mine/", VacancyMineAPIView.as_view(), name="vacancy-mine"),
    path("vacancies/<int:pk>/edit/", VacancyEditAPIView.as_view(), name="vacancy-edit"),
    path("vacancies/pending/", VacancyPendingListAPIView.as_view(), name="vacancy-pending"),
    path("moderation/vacancies/<int:pk>/", ModerationVacancyDetailAPIView.as_view(), name="moderation-vacancy-detail"),
    path("vacancies/<int:pk>/approve/", VacancyApproveAPIView.as_view(), name="vacancy-approve"),
    path("vacancies/<int:pk>/reject/", VacancyRejectAPIView.as_view(), name="vacancy-reject"),
    path("vacancies/<int:pk>/resubmit/", VacancyResubmitAPIView.as_view(), name="vacancy-resubmit"),
    path("vacancies/<int:pk>/pause/", VacancyOwnerPauseAPIView.as_view(), name="vacancy-owner-pause"),
    path("vacancies/<int:pk>/delete/", VacancyOwnerDeleteAPIView.as_view(), name="vacancy-owner-delete"),

    path("vacancies/<int:pk>/contacts/", VacancyContactAPIView.as_view()),
    path("vacancies/<int:pk>/contact-access-state/", VacancyContactAccessStateAPIView.as_view(), name="vacancy-contact-access-state"),
    path("vacancies/<int:pk>/review/", VacancyReviewAPIView.as_view(), name="vacancy-review"),
    path("employers/<int:owner_user_id>/profile/", EmployerProfileAPIView.as_view(), name="employer-profile"),
    path("employers/<int:owner_user_id>/reviews/moderator/", EmployerReviewModeratorListAPIView.as_view(), name="employer-reviews-moderator"),
    path("employers/<int:owner_user_id>/subscription/", EmployerSubscriptionAPIView.as_view(), name="employer-subscription"),
    path("employers/subscriptions/", EmployerSubscriptionListAPIView.as_view(), name="employer-subscription-list"),
    path("employers/search/", EmployerSearchAPIView.as_view(), name="employer-search"),
    path("vacancies/<int:pk>/block-owner/", VacancyBlockOwnerAPIView.as_view(), name="vacancy-block-owner"),
    path("user-blocks/", UserBlockListAPIView.as_view(), name="user-blocks"),
    path("user-blocks/<int:blocked_user_id>/", UserBlockRemoveAPIView.as_view(), name="user-block-remove"),

    path("vacancies/<int:pk>/unlock/request/", VacancyUnlockRequestAPIView.as_view(), name="vacancy-unlock-request"),
    path("vacancies/<int:pk>/unlock/confirm/", VacancyUnlockConfirmAPIView.as_view(), name="vacancy-unlock-confirm"),
    path("complaints/", ComplaintAPIView.as_view(), name="complaints"),
    path("moderation/complaints/", ComplaintListAPIView.as_view(), name="complaints-list"),
    path("moderation/complaints/by-vacancy/", ComplaintByVacancyAPIView.as_view(), name="complaints-by-vacancy"),
    path("moderation/complaints/<int:pk>/action/", ComplaintModerationActionAPIView.as_view(), name="complaint-action"),


]
