# Localized labels for employer web forms.
COUNTRY_LABELS = {'en': {'AD': 'Andorra',
        'AE': 'United Arab Emirates',
        'AL': 'Albania',
        'AM': 'Armenia',
        'AT': 'Austria',
        'AU': 'Australia',
        'AZ': 'Azerbaijan',
        'BA': 'Bosnia and Herzegovina',
        'BE': 'Belgium',
        'BG': 'Bulgaria',
        'BY': 'Belarus',
        'CA': 'Canada',
        'CH': 'Switzerland',
        'CY': 'Cyprus',
        'CZ': 'Czechia',
        'DE': 'Germany',
        'DK': 'Denmark',
        'EE': 'Estonia',
        'ES': 'Spain',
        'FI': 'Finland',
        'FR': 'France',
        'GE': 'Georgia',
        'GR': 'Greece',
        'HR': 'Croatia',
        'HU': 'Hungary',
        'IE': 'Ireland',
        'IL': 'Israel',
        'IS': 'Iceland',
        'IT': 'Italy',
        'KG': 'Kyrgyzstan',
        'KR': 'South Korea',
        'KZ': 'Kazakhstan',
        'LI': 'Liechtenstein',
        'LT': 'Lithuania',
        'LU': 'Luxembourg',
        'LV': 'Latvia',
        'MC': 'Monaco',
        'MD': 'Moldova',
        'ME': 'Montenegro',
        'MK': 'North Macedonia',
        'MT': 'Malta',
        'NL': 'Netherlands',
        'NO': 'Norway',
        'NZ': 'New Zealand',
        'OTHER': 'Other',
        'PL': 'Poland',
        'PT': 'Portugal',
        'QA': 'Qatar',
        'RO': 'Romania',
        'RS': 'Serbia',
        'SA': 'Saudi Arabia',
        'SE': 'Sweden',
        'SI': 'Slovenia',
        'SK': 'Slovakia',
        'SM': 'San Marino',
        'TJ': 'Tajikistan',
        'TR': 'Turkey',
        'UA': 'Ukraine',
        'UK': 'United Kingdom',
        'US': 'USA',
        'UZ': 'Uzbekistan',
        'XK': 'Kosovo'},
 'pl': {'AD': 'Andora',
        'AE': 'Zjednoczone Emiraty Arabskie',
        'AL': 'Albania',
        'AM': 'Armenia',
        'AT': 'Austria',
        'AU': 'Australia',
        'AZ': 'Azerbejdżan',
        'BA': 'Bośnia i Hercegowina',
        'BE': 'Belgia',
        'BG': 'Bułgaria',
        'BY': 'Białoruś',
        'CA': 'Kanada',
        'CH': 'Szwajcaria',
        'CY': 'Cypr',
        'CZ': 'Czechy',
        'DE': 'Niemcy',
        'DK': 'Dania',
        'EE': 'Estonia',
        'ES': 'Hiszpania',
        'FI': 'Finlandia',
        'FR': 'Francja',
        'GE': 'Gruzja',
        'GR': 'Grecja',
        'HR': 'Chorwacja',
        'HU': 'Węgry',
        'IE': 'Irlandia',
        'IL': 'Izrael',
        'IS': 'Islandia',
        'IT': 'Włochy',
        'KG': 'Kirgistan',
        'KR': 'Korea Południowa',
        'KZ': 'Kazachstan',
        'LI': 'Liechtenstein',
        'LT': 'Litwa',
        'LU': 'Luksemburg',
        'LV': 'Łotwa',
        'MC': 'Monako',
        'MD': 'Mołdawia',
        'ME': 'Czarnogóra',
        'MK': 'Macedonia Północna',
        'MT': 'Malta',
        'NL': 'Niderlandy',
        'NO': 'Norwegia',
        'NZ': 'Nowa Zelandia',
        'OTHER': 'Inne',
        'PL': 'Polska',
        'PT': 'Portugalia',
        'QA': 'Katar',
        'RO': 'Rumunia',
        'RS': 'Serbia',
        'SA': 'Arabia Saudyjska',
        'SE': 'Szwecja',
        'SI': 'Słowenia',
        'SK': 'Słowacja',
        'SM': 'San Marino',
        'TJ': 'Tadżykistan',
        'TR': 'Turcja',
        'UA': 'Ukraina',
        'UK': 'Wielka Brytania',
        'US': 'USA',
        'UZ': 'Uzbekistan',
        'XK': 'Kosowo'},
 'ru': {'AD': 'Андорра',
        'AE': 'ОАЭ',
        'AL': 'Албания',
        'AM': 'Армения',
        'AT': 'Австрия',
        'AU': 'Австралия',
        'AZ': 'Азербайджан',
        'BA': 'Босния и Герцеговина',
        'BE': 'Бельгия',
        'BG': 'Болгария',
        'BY': 'Беларусь',
        'CA': 'Канада',
        'CH': 'Швейцария',
        'CY': 'Кипр',
        'CZ': 'Чехия',
        'DE': 'Германия',
        'DK': 'Дания',
        'EE': 'Эстония',
        'ES': 'Испания',
        'FI': 'Финляндия',
        'FR': 'Франция',
        'GE': 'Грузия',
        'GR': 'Греция',
        'HR': 'Хорватия',
        'HU': 'Венгрия',
        'IE': 'Ирландия',
        'IL': 'Израиль',
        'IS': 'Исландия',
        'IT': 'Италия',
        'KG': 'Кыргызстан',
        'KR': 'Южная Корея',
        'KZ': 'Казахстан',
        'LI': 'Лихтенштейн',
        'LT': 'Литва',
        'LU': 'Люксембург',
        'LV': 'Латвия',
        'MC': 'Монако',
        'MD': 'Молдова',
        'ME': 'Черногория',
        'MK': 'Северная Македония',
        'MT': 'Мальта',
        'NL': 'Нидерланды',
        'NO': 'Норвегия',
        'NZ': 'Новая Зеландия',
        'OTHER': 'Другое',
        'PL': 'Польша',
        'PT': 'Португалия',
        'QA': 'Катар',
        'RO': 'Румыния',
        'RS': 'Сербия',
        'SA': 'Саудовская Аравия',
        'SE': 'Швеция',
        'SI': 'Словения',
        'SK': 'Словакия',
        'SM': 'Сан-Марино',
        'TJ': 'Таджикистан',
        'TR': 'Турция',
        'UA': 'Украина',
        'UK': 'Великобритания',
        'US': 'США',
        'UZ': 'Узбекистан',
        'XK': 'Косово'},
 'uk': {'AD': 'Андорра',
        'AE': 'ОАЕ',
        'AL': 'Албанія',
        'AM': 'Вірменія',
        'AT': 'Австрія',
        'AU': 'Австралія',
        'AZ': 'Азербайджан',
        'BA': 'Боснія і Герцеговина',
        'BE': 'Бельгія',
        'BG': 'Болгарія',
        'BY': 'Білорусь',
        'CA': 'Канада',
        'CH': 'Швейцарія',
        'CY': 'Кіпр',
        'CZ': 'Чехія',
        'DE': 'Німеччина',
        'DK': 'Данія',
        'EE': 'Естонія',
        'ES': 'Іспанія',
        'FI': 'Фінляндія',
        'FR': 'Франція',
        'GE': 'Грузія',
        'GR': 'Греція',
        'HR': 'Хорватія',
        'HU': 'Угорщина',
        'IE': 'Ірландія',
        'IL': 'Ізраїль',
        'IS': 'Ісландія',
        'IT': 'Італія',
        'KG': 'Киргизстан',
        'KR': 'Південна Корея',
        'KZ': 'Казахстан',
        'LI': 'Ліхтенштейн',
        'LT': 'Литва',
        'LU': 'Люксембург',
        'LV': 'Латвія',
        'MC': 'Монако',
        'MD': 'Молдова',
        'ME': 'Чорногорія',
        'MK': 'Північна Македонія',
        'MT': 'Мальта',
        'NL': 'Нідерланди',
        'NO': 'Норвегія',
        'NZ': 'Нова Зеландія',
        'OTHER': 'Інше',
        'PL': 'Польща',
        'PT': 'Португалія',
        'QA': 'Катар',
        'RO': 'Румунія',
        'RS': 'Сербія',
        'SA': 'Саудівська Аравія',
        'SE': 'Швеція',
        'SI': 'Словенія',
        'SK': 'Словаччина',
        'SM': 'Сан-Марино',
        'TJ': 'Таджикистан',
        'TR': 'Туреччина',
        'UA': 'Україна',
        'UK': 'Велика Британія',
        'US': 'США',
        'UZ': 'Узбекистан',
        'XK': 'Косово'}}
CATEGORY_LABELS = {'en': {'agriculture': 'Agriculture',
        'cleaning': 'Cleaning',
        'construction': 'Construction',
        'freelance': 'Freelance',
        'healthcare': 'Healthcare',
        'hospitality': 'Hospitality',
        'it': 'IT',
        'logistics': 'Logistics',
        'manufacturing': 'Manufacturing',
        'other': 'Other',
        'retail': 'Retail',
        'service': 'Service',
        'transport': 'Transport',
        'warehouse': 'Warehouse'},
 'pl': {'agriculture': 'Rolnictwo',
        'cleaning': 'Sprzątanie',
        'construction': 'Budownictwo',
        'freelance': 'Freelance',
        'healthcare': 'Opieka zdrowotna',
        'hospitality': 'Hotelarstwo i gastronomia',
        'it': 'IT',
        'logistics': 'Logistyka',
        'manufacturing': 'Produkcja',
        'other': 'Inne',
        'retail': 'Handel',
        'service': 'Usługi',
        'transport': 'Transport',
        'warehouse': 'Magazyn'},
 'ru': {'agriculture': 'Сельское хозяйство',
        'cleaning': 'Уборка',
        'construction': 'Строительство',
        'freelance': 'Фриланс',
        'healthcare': 'Медицина',
        'hospitality': 'Гостиницы и рестораны',
        'it': 'ИТ',
        'logistics': 'Логистика',
        'manufacturing': 'Производство',
        'other': 'Другое',
        'retail': 'Ритейл',
        'service': 'Сервис',
        'transport': 'Транспорт',
        'warehouse': 'Склад'},
 'uk': {'agriculture': 'Сільське господарство',
        'cleaning': 'Прибирання',
        'construction': 'Будівництво',
        'freelance': 'Фриланс',
        'healthcare': "Охорона здоров'я",
        'hospitality': 'Готельно-ресторанна сфера',
        'it': 'ІТ',
        'logistics': 'Логістика',
        'manufacturing': 'Виробництво',
        'other': 'Інше',
        'retail': 'Рітейл',
        'service': 'Сервіс',
        'transport': 'Транспорт',
        'warehouse': 'Склад'}}
EMPLOYMENT_LABELS = {'en': {'contract': 'Contract',
        'full': 'Full-time',
        'internship': 'Internship',
        'part': 'Part-time',
        'seasonal': 'Seasonal',
        'shift': 'Shift',
        'temporary': 'Temporary'},
 'pl': {'contract': 'Kontrakt',
        'full': 'Pełny etat',
        'internship': 'Staż',
        'part': 'Niepełny etat',
        'seasonal': 'Sezonowa',
        'shift': 'Zmiany',
        'temporary': 'Tymczasowa'},
 'ru': {'contract': 'Контракт',
        'full': 'Полная занятость',
        'internship': 'Стажировка',
        'part': 'Частичная занятость',
        'seasonal': 'Сезонная',
        'shift': 'Сменный график',
        'temporary': 'Временная'},
 'uk': {'contract': 'Контракт',
        'full': 'Повна зайнятість',
        'internship': 'Стажування',
        'part': 'Часткова зайнятість',
        'seasonal': 'Сезонна',
        'shift': 'Змінний графік',
        'temporary': 'Тимчасова'}}
EXPERIENCE_LABELS = {'en': {'with': 'With experience', 'without': 'Without experience'},
 'pl': {'with': 'Z doświadczeniem', 'without': 'Bez doświadczenia'},
 'ru': {'with': 'С опытом', 'without': 'Без опыта'},
 'uk': {'with': 'З досвідом', 'without': 'Без досвіду'}}
HOUSING_LABELS = {'en': {'free': 'Free', 'none': 'Not provided', 'paid': 'Paid'},
 'pl': {'free': 'Bezpłatne', 'none': 'Brak', 'paid': 'Płatne'},
 'ru': {'free': 'Бесплатно', 'none': 'Не предоставляется', 'paid': 'Платно'},
 'uk': {'free': 'Безкоштовно', 'none': 'Не надається', 'paid': 'Платно'}}
SOURCE_LABELS = {'en': {'agency': 'Agency', 'direct': 'Direct employer', 'other': 'Other'},
 'pl': {'agency': 'Agencja', 'direct': 'Bezpośredni pracodawca', 'other': 'Inne'},
 'ru': {'agency': 'Агентство', 'direct': 'Прямой работодатель', 'other': 'Другое'},
 'uk': {'agency': 'Агенція', 'direct': 'Прямий роботодавець', 'other': 'Інше'}}
SALARY_TAX_LABELS = {'en': {'brutto': 'Brutto', 'netto': 'Netto'},
 'pl': {'brutto': 'Brutto', 'netto': 'Netto'},
 'ru': {'brutto': 'Брутто', 'netto': 'Нетто'},
 'uk': {'brutto': 'Брутто', 'netto': 'Нетто'}}


def localized_choices(base_choices, labels, lang):
    lang_labels = labels.get(lang) or labels.get("ru") or {}
    return [(value, lang_labels.get(value, label)) for value, label in base_choices]


def localized_country_choices(base_choices, lang):
    return localized_choices(base_choices, COUNTRY_LABELS, lang)
