"""Support data models are introduced package by package.

Keeping them in a separate package prevents the public JobHub ``jobs.models``
module from becoming the source of truth for Support operations.
"""

from .audit import AuditEvent
from .entitlement import SupportAccessExtensionRequest, SupportAccessGrant
from .organization import (
    DelegablePermissionGrant,
    InvitationPermissionGrant,
    MembershipInvitation,
    OrganizationMembership,
    PermissionGrant,
    SupportOrganization,
)
from .messaging import (
    SupportConversation,
    SupportConversationReport,
    SupportConversationMember,
    SupportMessage,
    SupportMessageTranslation,
)
from .notifications import InAppNotification, NotificationOutbox, PushDelivery
from .operations import (
    DriverVehicleAssignment,
    HousingAssignment,
    HousingPlace,
    HousingRoom,
    HousingSite,
    RouteStop,
    TransportCrew,
    TransportCrewDriver,
    TransportCrewMember,
    TransportCrewResourceOverride,
    TransportCrewScheduleOverride,
    TransportCrewVehicle,
    TransportPassengerAssignment,
    TransportRoute,
    Vehicle,
    WorkerProjectAssignment,
    ProjectScheduleTemplate,
    WorkerAccessScope,
    WorkProject,
    Worksite,
)
from .pipeline import (
    ApplicationDecisionEvent,
    BotContentRevision,
    ConnectionStageEvent,
    EmploymentExclusivityLock,
    PartnerPairRequest,
    SupportApplicantReference,
    SupportApplication,
    SupportConnection,
    SupportVacancy,
)
from .project_crews import (
    ProjectCrew,
    ProjectCrewDriverSubstitution,
    ProjectCrewMemberAbsence,
    ProjectCrewPassenger,
    ProjectCrewResourceAssignment,
    ProjectCrewShift,
    ProjectCrewShiftMember,
    WorkerScheduleDayOff,
)
from .timekeeping import (
    CalendarMarkBatch,
    CalendarMarkBatchItem,
    CalendarMarkTemplate,
    ScheduledShiftBatch,
    ScheduledWorkShift,
    ShiftTemplate,
    WorkTimeEntry,
    WorkTimeEntryRevision,
)
from .worker_requests import WorkerRequest, WorkerRequestDate, WorkerRequestEvent
from .tasks import (
    Announcement,
    AnnouncementAcknowledgement,
    ContentTemplate,
    TaskAssignment,
    WorkerTask,
)
from .documents import (
    DocumentRequestPackage,
    DocumentRequestPackageEvent,
    SupportWorkerDocumentReference,
)

__all__ = [
    "AuditEvent",
    "CalendarMarkBatch",
    "CalendarMarkBatchItem",
    "CalendarMarkTemplate",
    "ContentTemplate",
    "Announcement",
    "AnnouncementAcknowledgement",
    "ApplicationDecisionEvent",
    "BotContentRevision",
    "ConnectionStageEvent",
    "DelegablePermissionGrant",
    "DocumentRequestPackage",
    "DocumentRequestPackageEvent",
    "DriverVehicleAssignment",
    "EmploymentExclusivityLock",
    "HousingAssignment",
    "HousingPlace",
    "HousingRoom",
    "HousingSite",
    "InvitationPermissionGrant",
    "InAppNotification",
    "MembershipInvitation",
    "OrganizationMembership",
    "NotificationOutbox",
    "PermissionGrant",
    "PartnerPairRequest",
    "ProjectCrew",
    "ProjectCrewDriverSubstitution",
    "ProjectCrewMemberAbsence",
    "ProjectCrewPassenger",
    "ProjectCrewResourceAssignment",
    "ProjectCrewShift",
    "ProjectCrewShiftMember",
    "PushDelivery",
    "RouteStop",
    "TransportCrew",
    "TransportCrewDriver",
    "TransportCrewMember",
    "TransportCrewResourceOverride",
    "TransportCrewScheduleOverride",
    "TransportCrewVehicle",
    "SupportAccessExtensionRequest",
    "SupportAccessGrant",
    "SupportApplicantReference",
    "SupportApplication",
    "SupportConnection",
    "SupportConversation",
    "SupportConversationReport",
    "SupportConversationMember",
    "SupportMessage",
    "SupportMessageTranslation",
    "SupportOrganization",
    "SupportVacancy",
    "SupportWorkerDocumentReference",
    "TaskAssignment",
    "ScheduledWorkShift",
    "ScheduledShiftBatch",
    "ShiftTemplate",
    "TransportPassengerAssignment",
    "TransportRoute",
    "Vehicle",
    "WorkerProjectAssignment",
    "WorkerScheduleDayOff",
    "ProjectScheduleTemplate",
    "WorkerAccessScope",
    "WorkProject",
    "Worksite",
    "WorkTimeEntry",
    "WorkTimeEntryRevision",
    "WorkerRequest",
    "WorkerRequestDate",
    "WorkerRequestEvent",
    "WorkerTask",
]
